<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AtencionSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('TRUNCATE TABLE atencion RESTART IDENTITY CASCADE');

        $data = [
            // SEMANA 1
            [
                'idrequerimiento' => 1,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Web Admisión Q2',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/banner_q2.png',
                'fechacreacion' => '2026-05-01 09:00:00',
                'fechainicio' => '2026-05-02 09:00:00',
                'fechafin' => '2026-05-04 10:00:00',
                'fechacompletado' => '2026-05-04 11:30:00',
            ],
            [
                'idrequerimiento' => 2,
                'idadmin' => 1,
                'idempleado' => 2,
                'idservicio' => 4,
                'idarea_agencia' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Sesión Retratos Docentes',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/retratos.zip',
                'fechacreacion' => '2026-05-01 10:00:00',
                'fechainicio' => '2026-05-02 10:00:00',
                'fechafin' => '2026-05-04 14:00:00',
                'fechacompletado' => '2026-05-04 15:00:00',
            ],
            [
                'idrequerimiento' => 3,
                'idadmin' => 1,
                'idempleado' => 6,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Plan Content Mayo',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/plan_mayo.pdf',
                'fechacreacion' => '2026-05-01 11:00:00',
                'fechainicio' => '2026-05-02 11:00:00',
                'fechafin' => '2026-05-04 16:00:00',
                'fechacompletado' => '2026-05-04 17:00:00',
            ],
            [
                'idrequerimiento' => 4,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Taller Padres',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/flyer_taller.jpg',
                'fechacreacion' => '2026-05-02 09:00:00',
                'fechainicio' => '2026-05-03 09:00:00',
                'fechafin' => '2026-05-05 10:00:00',
                'fechacompletado' => '2026-05-05 12:00:00',
            ],
            [
                'idrequerimiento' => 5,
                'idadmin' => 1,
                'idempleado' => 9,
                'idservicio' => 2,
                'idarea_agencia' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Video Institucional Short',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'url_entrega' => 'https://drive.google.com/delivery/video_short.mp4',
                'fechacreacion' => '2026-05-02 10:00:00',
                'fechainicio' => '2026-05-03 10:00:00',
                'fechafin' => '2026-05-05 15:00:00',
                'fechacompletado' => '2026-05-05 17:30:00',
            ],
            [
                'idrequerimiento' => 6,
                'idadmin' => 1,
                'idempleado' => 2,
                'idservicio' => 4,
                'idarea_agencia' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Evento Deportivo',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/fotos_deporte.zip',
                'fechacreacion' => '2026-05-03 09:00:00',
                'fechainicio' => '2026-05-04 09:00:00',
                'fechafin' => '2026-05-06 10:00:00',
                'fechacompletado' => '2026-05-06 11:00:00',
            ],
            [
                'idrequerimiento' => 7,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Catálogo Invierno',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/catalogo.pdf',
                'fechacreacion' => '2026-05-03 10:00:00',
                'fechainicio' => '2026-05-04 10:00:00',
                'fechafin' => '2026-05-06 14:00:00',
                'fechacompletado' => '2026-05-06 15:00:00',
            ],
            [
                'idrequerimiento' => 8,
                'idadmin' => 1,
                'idempleado' => 4,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Copywriting Ads',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/copys.docx',
                'fechacreacion' => '2026-05-03 11:00:00',
                'fechainicio' => '2026-05-04 11:00:00',
                'fechafin' => '2026-05-06 16:00:00',
                'fechacompletado' => '2026-05-06 17:00:00',
            ],
            [
                'idrequerimiento' => 9,
                'idadmin' => 1,
                'idempleado' => 3,
                'idservicio' => null,
                'idarea_agencia' => 3,
                'servicio_personalizado' => 'Consultoría Estratégica',
                'titulo' => 'Plan Fidelización',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/plan_fidelizacion.pdf',
                'fechacreacion' => '2026-05-03 14:00:00',
                'fechainicio' => '2026-05-04 14:00:00',
                'fechafin' => '2026-05-06 18:00:00',
                'fechacompletado' => '2026-05-06 18:30:00',
            ],
            [
                'idrequerimiento' => 10,
                'idadmin' => 1,
                'idempleado' => 8,
                'idservicio' => 2,
                'idarea_agencia' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Motion Graphic Logo',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/logo_motion.mp4',
                'fechacreacion' => '2026-05-04 09:00:00',
                'fechainicio' => '2026-05-05 09:00:00',
                'fechafin' => '2026-05-07 10:00:00',
                'fechacompletado' => '2026-05-07 11:30:00',
            ],
            [
                'idrequerimiento' => 11,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Diploma Honor',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/diploma.pdf',
                'fechacreacion' => '2026-05-04 10:00:00',
                'fechainicio' => '2026-05-05 10:00:00',
                'fechafin' => '2026-05-07 14:00:00',
                'fechacompletado' => '2026-05-07 15:00:00',
            ],
            [
                'idrequerimiento' => 12,
                'idadmin' => 1,
                'idempleado' => 2,
                'idservicio' => 4,
                'idarea_agencia' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Stock Local',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/fotos_stock.zip',
                'fechacreacion' => '2026-05-04 11:00:00',
                'fechainicio' => '2026-05-05 11:00:00',
                'fechafin' => '2026-05-07 16:00:00',
                'fechacompletado' => '2026-05-07 17:00:00',
            ],
            [
                'idrequerimiento' => 13,
                'idadmin' => 1,
                'idempleado' => 5,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Post Día Madre',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/post_madre.jpg',
                'fechacreacion' => '2026-05-05 09:00:00',
                'fechainicio' => '2026-05-06 09:00:00',
                'fechafin' => '2026-05-08 10:00:00',
                'fechacompletado' => '2026-05-08 12:00:00',
            ],
            [
                'idrequerimiento' => 14,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Etiquetas Productos',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'url_entrega' => 'https://drive.google.com/delivery/etiquetas.pdf',
                'fechacreacion' => '2026-05-05 10:00:00',
                'fechainicio' => '2026-05-06 10:00:00',
                'fechafin' => '2026-05-08 15:00:00',
                'fechacompletado' => '2026-05-08 17:00:00',
            ],
            [
                'idrequerimiento' => 15,
                'idadmin' => 1,
                'idempleado' => 7,
                'idservicio' => 2,
                'idarea_agencia' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Intro YouTube',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/intro.mp4',
                'fechacreacion' => '2026-05-05 11:00:00',
                'fechainicio' => '2026-05-06 11:00:00',
                'fechafin' => '2026-05-08 17:30:00',
                'fechacompletado' => '2026-05-08 18:30:00',
            ],
            // SEMANA 2
            [
                'idrequerimiento' => 16,
                'idadmin' => 1,
                'idempleado' => 2,
                'idservicio' => 4,
                'idarea_agencia' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Outdoor',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/fotos_outdoor.zip',
                'fechacreacion' => '2026-05-08 09:00:00',
                'fechainicio' => '2026-05-09 09:00:00',
                'fechafin' => '2026-05-11 10:00:00',
                'fechacompletado' => '2026-05-11 11:00:00',
            ],
            [
                'idrequerimiento' => 17,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Sale',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/banner_sale.png',
                'fechacreacion' => '2026-05-08 10:00:00',
                'fechainicio' => '2026-05-09 10:00:00',
                'fechafin' => '2026-05-11 14:00:00',
                'fechacompletado' => '2026-05-11 15:00:00',
            ],
            [
                'idrequerimiento' => 18,
                'idadmin' => 1,
                'idempleado' => 6,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Artículos Blog',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/blog_articles.zip',
                'fechacreacion' => '2026-05-08 11:00:00',
                'fechainicio' => '2026-05-09 11:00:00',
                'fechafin' => '2026-05-11 16:00:00',
                'fechacompletado' => '2026-05-11 17:00:00',
            ],
            [
                'idrequerimiento' => 19,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => null,
                'idarea_agencia' => 1,
                'servicio_personalizado' => 'Rebranding Logo',
                'titulo' => 'Propuesta Logo 2',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'url_entrega' => 'https://drive.google.com/delivery/logo_v2.pdf',
                'fechacreacion' => '2026-05-08 14:00:00',
                'fechainicio' => '2026-05-09 14:00:00',
                'fechafin' => '2026-05-11 18:00:00',
                'fechacompletado' => '2026-05-11 18:30:00',
            ],
            [
                'idrequerimiento' => 20,
                'idadmin' => 1,
                'idempleado' => 7,
                'idservicio' => 2,
                'idarea_agencia' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Loop Vitrina',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/loop_vitrina.mp4',
                'fechacreacion' => '2026-05-09 09:00:00',
                'fechainicio' => '2026-05-10 09:00:00',
                'fechafin' => '2026-05-12 10:00:00',
                'fechacompletado' => '2026-05-12 12:00:00',
            ],
            [
                'idrequerimiento' => 21,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Tarjeta Presentación',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/tarjeta.pdf',
                'fechacreacion' => '2026-05-09 10:00:00',
                'fechainicio' => '2026-05-10 10:00:00',
                'fechafin' => '2026-05-12 15:00:00',
                'fechacompletado' => '2026-05-12 17:00:00',
            ],
            [
                'idrequerimiento' => 22,
                'idadmin' => 1,
                'idempleado' => 2,
                'idservicio' => 4,
                'idarea_agencia' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Productos',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/fotos_prod.zip',
                'fechacreacion' => '2026-05-10 09:00:00',
                'fechainicio' => '2026-05-11 09:00:00',
                'fechafin' => '2026-05-13 10:00:00',
                'fechacompletado' => '2026-05-13 11:30:00',
            ],
            [
                'idrequerimiento' => 23,
                'idadmin' => 1,
                'idempleado' => 4,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'News Mensual',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/news.pdf',
                'fechacreacion' => '2026-05-10 10:00:00',
                'fechainicio' => '2026-05-11 10:00:00',
                'fechafin' => '2026-05-13 14:00:00',
                'fechacompletado' => '2026-05-13 15:30:00',
            ],
            [
                'idrequerimiento' => 24,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Señalética Nueva',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/senaletica.pdf',
                'fechacreacion' => '2026-05-10 11:00:00',
                'fechainicio' => '2026-05-11 11:00:00',
                'fechafin' => '2026-05-13 17:00:00',
                'fechacompletado' => '2026-05-13 18:00:00',
            ],
            [
                'idrequerimiento' => 25,
                'idadmin' => 1,
                'idempleado' => 9,
                'idservicio' => 2,
                'idarea_agencia' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Reel Promo 14',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'url_entrega' => 'https://drive.google.com/delivery/reel_14.mp4',
                'fechacreacion' => '2026-05-11 09:00:00',
                'fechainicio' => '2026-05-12 09:00:00',
                'fechafin' => '2026-05-14 10:00:00',
                'fechacompletado' => '2026-05-14 12:00:00',
            ],
            [
                'idrequerimiento' => 26,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Manual Identidad Lite',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/manual_lite.pdf',
                'fechacreacion' => '2026-05-11 10:00:00',
                'fechainicio' => '2026-05-12 10:00:00',
                'fechafin' => '2026-05-14 14:00:00',
                'fechacompletado' => '2026-05-14 15:00:00',
            ],
            [
                'idrequerimiento' => 27,
                'idadmin' => 1,
                'idempleado' => 6,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Estrategia Reels Mayo',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'url_entrega' => 'https://drive.google.com/delivery/estrategia_mayo.pdf',
                'fechacreacion' => '2026-05-11 11:00:00',
                'fechainicio' => '2026-05-12 11:00:00',
                'fechafin' => '2026-05-14 16:00:00',
                'fechacompletado' => '2026-05-14 17:00:00',
            ],
        ];

        $this->db->table('atencion')->insertBatch($data);
    }
}