<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AtencionSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('TRUNCATE TABLE atencion RESTART IDENTITY CASCADE');

        $data = [

            /* UAI  */

            // ADMINISTRACIÓN FINANCIERA Y TALENTO HUMANO
            [
                'idrequerimiento' => 1,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Piezas Días Festivos Febrero 2026 – Talento Humano',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_th/piezas_festivos_febrero.jpg',
                'fechacreacion' => '2026-01-26 10:00:00',
                'fechainicio' => '2026-01-27 09:00:00',
                'fechafin' => '2026-01-29 18:00:00',
                'fechacompletado' => '2026-01-29 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 2,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Formulario Identificación Miembros de Mesa – Colaboradores',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_th/form_miembros_mesa.jpg',
                'fechacreacion' => '2026-01-27 09:00:00',
                'fechainicio' => '2026-01-27 11:00:00',
                'fechafin' => '2026-01-29 18:00:00',
                'fechacompletado' => '2026-01-29 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 3,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Invitación After Office – Día del Trabajador 29/04',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se cambió el nombre del restaurante a "El Olivar" y se añadió hora 7:00 p.m.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_th/invitacion_after_office_dia_madre.jpg',
                'fechacreacion' => '2026-04-27 10:00:00',
                'fechainicio' => '2026-04-27 14:00:00',
                'fechafin' => '2026-04-29 18:00:00',
                'fechacompletado' => '2026-04-29 17:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 4,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Capacitación Virtual "Procedimientos Administrativos en Atención al Público"',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_th/capacitacion_procedimientos_adm.jpg',
                'fechacreacion' => '2026-02-09 09:00:00',
                'fechainicio' => '2026-02-09 11:00:00',
                'fechafin' => '2026-02-10 18:00:00',
                'fechacompletado' => '2026-02-10 16:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // ÁREA COMERCIAL
            [
                'idrequerimiento' => 5,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Convenio Institucional – Policía Nacional del Perú',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se ajustó el 30% de descuento en tamaño y se añadió listado de programas de posgrado.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_comercial/flyer_convenio_pnp.jpg',
                'fechacreacion' => '2026-03-10 09:00:00',
                'fechainicio' => '2026-03-10 11:00:00',
                'fechafin' => '2026-03-12 18:00:00',
                'fechacompletado' => '2026-03-12 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 6,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Plantilla Charla Virtual Posgrado – Editable Canva',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_comercial/plantilla_charla_virtual_canva.png',
                'fechacreacion' => '2026-02-18 10:00:00',
                'fechainicio' => '2026-02-18 14:00:00',
                'fechafin' => '2026-02-21 18:00:00',
                'fechacompletado' => '2026-02-21 13:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 7,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Guía Rápida Pregrado A5 – Actualización Campus y Modalidades',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => 'Primera revisión: eliminar sección talleres. Segunda revisión: ajustar logos de modalidades.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_comercial/guia_rapida_pregrado_a5.pdf',
                'fechacreacion' => '2026-05-18 09:00:00',
                'fechainicio' => '2026-05-18 10:30:00',
                'fechafin' => '2026-05-20 18:00:00',
                'fechacompletado' => '2026-05-20 17:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 8,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Convenio Corporativo Colegio de Obstetras de Huánuco',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_comercial/flyer_obstetras_huanuco.jpg',
                'fechacreacion' => '2026-02-18 11:00:00',
                'fechainicio' => '2026-02-19 09:00:00',
                'fechafin' => '2026-02-21 18:00:00',
                'fechacompletado' => '2026-02-21 11:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 9,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Examen de Admisión Pregrado 27 de junio',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se ajustó tipografía y se destacó la fecha 27/06 con mayor tamaño.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_comercial/flyer_admision_27jun.jpg',
                'fechacreacion' => '2026-06-07 09:00:00',
                'fechainicio' => '2026-06-07 10:30:00',
                'fechafin' => '2026-06-09 18:00:00',
                'fechacompletado' => '2026-06-09 16:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // BIENESTAR UNIVERSITARIO
            [
                'idrequerimiento' => 10,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Postulación Beneficios Económicos 2026-1',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_bienestar/banner_beneficios_2026-1.jpg',
                'fechacreacion' => '2026-01-08 09:00:00',
                'fechainicio' => '2026-01-08 10:30:00',
                'fechafin' => '2026-01-10 18:00:00',
                'fechacompletado' => '2026-01-10 16:45:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 11,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Comunicado Matrícula Regular Beneficios Económicos',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_bienestar/comunicado_matricula_regular.jpg',
                'fechacreacion' => '2026-01-28 10:00:00',
                'fechainicio' => '2026-01-28 11:00:00',
                'fechafin' => '2026-01-30 18:00:00',
                'fechacompletado' => '2026-01-30 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 12,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Tutores Psicólogos Servicio Psicopedagógico',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_bienestar/convocatoria_tutores_psi.jpg',
                'fechacreacion' => '2026-01-28 14:00:00',
                'fechainicio' => '2026-01-29 09:00:00',
                'fechafin' => '2026-01-31 18:00:00',
                'fechacompletado' => '2026-01-31 14:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 13,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Deportistas Alta Competencia 2026-1',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Cliente solicitó añadir disciplinas: atletismo y tenis de mesa.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_bienestar/conv_deportistas_alta_comp.jpg',
                'fechacreacion' => '2026-01-28 09:30:00',
                'fechainicio' => '2026-01-29 10:00:00',
                'fechafin' => '2026-01-31 18:00:00',
                'fechacompletado' => '2026-01-31 17:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 14,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Inicio Talleres Deportivos 2026-I – Sede Chincha',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió logo del Servicio Deportivo en segunda versión.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_bienestar/talleres_deportivos_chincha.jpg',
                'fechacreacion' => '2026-04-06 09:00:00',
                'fechainicio' => '2026-04-07 09:00:00',
                'fechafin' => '2026-04-09 18:00:00',
                'fechacompletado' => '2026-04-09 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 15,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Comunicado Uso Correcto de Botiquines de Seguridad',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_bienestar/comunicado_botiquines.jpg',
                'fechacreacion' => '2026-05-08 11:00:00',
                'fechainicio' => '2026-05-08 11:30:00',
                'fechafin' => '2026-05-08 18:00:00',
                'fechacompletado' => '2026-05-08 17:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // COBRANZAS Y CAJA
            [
                'idrequerimiento' => 16,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Recordatorio 1ª Cuota Pregrado y Posgrado – Vence 13 de Abril',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se generaron 4 versiones por sede con canales de pago diferenciados.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_cobranzas/recordatorio_1ra_cuota_abril.jpg',
                'fechacreacion' => '2026-04-01 09:00:00',
                'fechainicio' => '2026-04-01 11:00:00',
                'fechafin' => '2026-04-05 18:00:00',
                'fechacompletado' => '2026-04-05 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 17,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Canales de Pago UAI 2026 – Volante A6 por Sede',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió información de mora S/. 0.12/día y advertencia de digitación correcta.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_cobranzas/volante_canales_pago_a6.pdf',
                'fechacreacion' => '2026-05-25 09:00:00',
                'fechainicio' => '2026-05-25 11:00:00',
                'fechafin' => '2026-05-28 18:00:00',
                'fechacompletado' => '2026-05-28 16:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 18,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Físico Canales de Pago – Módulos de Atención',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_cobranzas/banner_canales_pago_modulos.pdf',
                'fechacreacion' => '2026-04-18 10:00:00',
                'fechainicio' => '2026-04-18 14:00:00',
                'fechafin' => '2026-04-22 18:00:00',
                'fechacompletado' => '2026-04-22 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // COORDINACIÓN ADMINISTRATIVA Y ACADÉMICA – FICA
            [
                'idrequerimiento' => 19,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Concurso Público Selección Docente – FICA 2026-1',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_fica/flyer_concurso_docente_fica.jpg',
                'fechacreacion' => '2026-02-09 09:00:00',
                'fechainicio' => '2026-02-09 11:30:00',
                'fechafin' => '2026-02-11 18:00:00',
                'fechacompletado' => '2026-02-11 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 20,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Plantilla Guías de Laboratorio por Escuela Profesional – FICA',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se ajustaron colores identificadores por carrera según indicaciones del Decano.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_fica/plantilla_guia_laboratorio_fica.pdf',
                'fechacreacion' => '2026-02-20 10:00:00',
                'fechainicio' => '2026-02-20 14:00:00',
                'fechafin' => '2026-02-24 18:00:00',
                'fechacompletado' => '2026-02-24 17:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 21,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Comunicado Clases Virtuales Sábado 6 de Junio – Elecciones 2026',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_fica/comunicado_clases_virtuales_elecciones.jpg',
                'fechacreacion' => '2026-06-01 09:00:00',
                'fechainicio' => '2026-06-01 10:30:00',
                'fechafin' => '2026-06-02 18:00:00',
                'fechacompletado' => '2026-06-02 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // DEFENSORÍA UNIVERSITARIA
            [
                'idrequerimiento' => 22,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Afiche Institucional Tolerancia Cero al Hostigamiento Sexual',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se ajustó tipografía y tamaño para impresión con protector acrílico.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_defensoria/afiche_tolerancia_cero.pdf',
                'fechacreacion' => '2026-01-27 10:00:00',
                'fechainicio' => '2026-01-27 14:00:00',
                'fechafin' => '2026-01-30 18:00:00',
                'fechacompletado' => '2026-01-30 17:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 23,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer "¿Conoces tus Derechos Universitarios?" – Defensoría',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_defensoria/flyer_derechos_universitarios.jpg',
                'fechacreacion' => '2026-04-14 09:00:00',
                'fechainicio' => '2026-04-14 11:00:00',
                'fechafin' => '2026-04-17 18:00:00',
                'fechacompletado' => '2026-04-17 14:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 24,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner "Tolerancia Cero" 2x1 – Defensoría (para afiche físico)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió ícono de "comunidad respetuosa" y se verificaron dimensiones 2×1 m.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_defensoria/banner_tolerancia_cero_2x1.pdf',
                'fechacreacion' => '2026-05-06 11:00:00',
                'fechainicio' => '2026-05-06 14:00:00',
                'fechafin' => '2026-05-09 18:00:00',
                'fechacompletado' => '2026-05-09 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // DIRECCIÓN DE CALIDAD
            [
                'idrequerimiento' => 25,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Encuesta de Satisfacción Matrícula 2026-I – Estudiantes',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_calidad/encuesta_satisfaccion_matricula.jpg',
                'fechacreacion' => '2026-03-14 09:00:00',
                'fechainicio' => '2026-03-14 11:00:00',
                'fechafin' => '2026-03-18 18:00:00',
                'fechacompletado' => '2026-03-18 13:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 26,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Capacitación Acreditación SINEACE – Comités de Calidad 23 y 24 de Abril',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió Aula 401-D y el requisito de asistencia 100% para certificación.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_calidad/capacitacion_sineace_abril.jpg',
                'fechacreacion' => '2026-04-10 10:00:00',
                'fechainicio' => '2026-04-10 14:00:00',
                'fechafin' => '2026-04-14 18:00:00',
                'fechacompletado' => '2026-04-14 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 27,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Capacitación ISO 21001 – Gestión de Riesgos con PUCP (1-2 junio)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_calidad/capacitacion_iso21001_pucp.jpg',
                'fechacreacion' => '2026-05-14 11:00:00',
                'fechainicio' => '2026-05-15 09:00:00',
                'fechafin' => '2026-05-18 18:00:00',
                'fechacompletado' => '2026-05-18 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // MARKETING Y DISEÑO
            [
                'idrequerimiento' => 28,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Creación Logo CreaLab',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => 'Primera revisión: ajustar tipografía a fuente sans-serif sobria. Segunda revisión: corrección de paleta colores primarios.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_mkt/logo_crealab.png',
                'fechacreacion' => '2026-01-22 10:00:00',
                'fechainicio' => '2026-01-22 14:00:00',
                'fechafin' => '2026-01-25 18:00:00',
                'fechacompletado' => '2026-01-25 17:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 29,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Ciclo Cero "Contigo desde el Inicio" – Onboarding Cachimbos 2026-1',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió íconos de competencias digitales y se ajustó la paleta azul noche.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_mkt/flyer_ciclo_cero_cachimbos.jpg',
                'fechacreacion' => '2026-01-22 11:00:00',
                'fechainicio' => '2026-01-23 09:00:00',
                'fechafin' => '2026-01-25 18:00:00',
                'fechacompletado' => '2026-01-25 15:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 30,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Propuestas de Logo para Consultora Clienza',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se entregaron 3 propuestas; cliente eligió la opción 2 con ajuste de tipografía.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_mkt/logos_clienza_propuestas.pdf',
                'fechacreacion' => '2026-02-20 09:00:00',
                'fechainicio' => '2026-02-20 11:00:00',
                'fechafin' => '2026-02-23 18:00:00',
                'fechacompletado' => '2026-02-23 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // RESPONSABILIDAD SOCIAL
            [
                'idrequerimiento' => 31,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Voluntariado Universitario 2026-1',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_rs/conv_voluntariado_2026-1.jpg',
                'fechacreacion' => '2026-04-01 09:00:00',
                'fechainicio' => '2026-04-01 11:00:00',
                'fechafin' => '2026-04-05 18:00:00',
                'fechacompletado' => '2026-04-05 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 32,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Reciclatón UAI 2026 – Día Mundial del Reciclaje',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió la sede Ica en el diseño final.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_rs/reciclaton_uai_2026.jpg',
                'fechacreacion' => '2026-05-11 09:00:00',
                'fechainicio' => '2026-05-11 11:00:00',
                'fechafin' => '2026-05-14 18:00:00',
                'fechacompletado' => '2026-05-14 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 33,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Tótem Triangular – Inclusión, Diversidad e Identidad de Género',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => 'Primera revisión: ajustar escala 0.50 cm × 2 m. Segunda revisión: corrección de paleta de colores inclusivos.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_rs/totem_inclusion_diversidad.pdf',
                'fechacreacion' => '2026-04-10 10:00:00',
                'fechainicio' => '2026-04-10 14:00:00',
                'fechafin' => '2026-04-14 18:00:00',
                'fechacompletado' => '2026-04-14 17:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 34,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Pieza Gráfica "¿Cómo es la Responsabilidad Social en la UAI?"',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_rs/pieza_rs_uai.jpg',
                'fechacreacion' => '2026-04-18 11:00:00',
                'fechainicio' => '2026-04-20 09:00:00',
                'fechafin' => '2026-04-22 18:00:00',
                'fechacompletado' => '2026-04-22 13:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 35,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'ECOCANJE UAI – Filial Ica',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_rs/ecocanje_filial_ica.jpg',
                'fechacreacion' => '2026-05-29 09:00:00',
                'fechainicio' => '2026-05-29 11:00:00',
                'fechafin' => '2026-06-02 18:00:00',
                'fechacompletado' => '2026-06-02 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // TÓPICO / SERVICIO DE SALUD
            [
                'idrequerimiento' => 36,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Adaptación Flyer Afiliación SIS – Campus Ica',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_topico/flyer_afiliacion_sis_ica.jpg',
                'fechacreacion' => '2026-01-15 09:00:00',
                'fechainicio' => '2026-01-15 10:00:00',
                'fechafin' => '2026-01-17 18:00:00',
                'fechacompletado' => '2026-01-17 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 37,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Campaña Día Mundial del Glaucoma – Colaboradores UAI',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_topico/campaña_glaucoma.jpg',
                'fechacreacion' => '2026-03-04 10:00:00',
                'fechainicio' => '2026-03-05 09:00:00',
                'fechafin' => '2026-03-08 18:00:00',
                'fechacompletado' => '2026-03-08 12:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 38,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Horario de Atención Tópico Sede Chincha – Celtex',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_topico/horario_topico_chincha_celtex.pdf',
                'fechacreacion' => '2026-04-25 11:00:00',
                'fechainicio' => '2026-04-25 14:00:00',
                'fechafin' => '2026-04-28 18:00:00',
                'fechacompletado' => '2026-04-28 11:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 39,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => '1ª Campaña de Salud "Evita el Daño: Dile No a la Automedicación" – Campus Ica',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió el link de Zoom y se ajustó el orden de fechas (virtual 23/05 / presencial 25/05).',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_topico/campaña_automedicacion_ica.jpg',
                'fechacreacion' => '2026-05-13 09:00:00',
                'fechainicio' => '2026-05-13 11:00:00',
                'fechafin' => '2026-05-17 18:00:00',
                'fechacompletado' => '2026-05-17 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 40,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Cartel Técnicas de Lavado de Manos – Celtex',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_topico/cartel_lavado_manos_celtex.pdf',
                'fechacreacion' => '2026-04-25 14:00:00',
                'fechainicio' => '2026-04-26 09:00:00',
                'fechafin' => '2026-04-28 18:00:00',
                'fechacompletado' => '2026-04-28 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // REGISTROS ACADÉMICOS
            [
                'idrequerimiento' => 41,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Carné Universitario 2026-1',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_registros/conv_carne_universitario.jpg',
                'fechacreacion' => '2026-04-14 09:00:00',
                'fechainicio' => '2026-04-14 11:30:00',
                'fechafin' => '2026-04-17 18:00:00',
                'fechacompletado' => '2026-04-17 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // VÍNCULO UNIVERSITARIO
            [
                'idrequerimiento' => 42,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Fondo Zoom Institucional – Interior y Exterior',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se añadió versión internacional con texto "UAI – Perú" en ambos idiomas.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_vue/fondo_zoom_institucional.png',
                'fechacreacion' => '2026-01-27 09:00:00',
                'fechainicio' => '2026-01-27 11:00:00',
                'fechafin' => '2026-01-30 18:00:00',
                'fechacompletado' => '2026-01-30 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 43,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Plantilla Modelo Oferta Laboral – Estudiantes y Egresados',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_vue/plantilla_oferta_laboral.jpg',
                'fechacreacion' => '2026-02-18 10:00:00',
                'fechainicio' => '2026-02-18 14:00:00',
                'fechafin' => '2026-02-22 18:00:00',
                'fechacompletado' => '2026-02-22 12:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 44,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Movilidad Internacional Académica y Pasantías 2026',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se actualizaron las fechas de postulación para el período 2026.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_vue/conv_movilidad_internacional.jpg',
                'fechacreacion' => '2026-02-20 09:00:00',
                'fechainicio' => '2026-02-20 11:00:00',
                'fechafin' => '2026-02-24 18:00:00',
                'fechacompletado' => '2026-02-24 16:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // ESCUELA DE POSGRADO
            [
                'idrequerimiento' => 45,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Proceso de Matrícula Posgrado 2026-1',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_epg/matricula_posgrado_2026-1.jpg',
                'fechacreacion' => '2026-03-14 09:00:00',
                'fechainicio' => '2026-03-14 11:00:00',
                'fechafin' => '2026-03-18 18:00:00',
                'fechacompletado' => '2026-03-18 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 46,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Conferencia Virtual Posgrado – Psicología del Amor y Relaciones de Pareja',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se actualizó la hora de inicio a 7:00 p.m. y se añadió datos del ponente.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_epg/conferencia_psicologia_amor.jpg',
                'fechacreacion' => '2026-02-27 10:00:00',
                'fechainicio' => '2026-02-27 14:00:00',
                'fechafin' => '2026-03-02 18:00:00',
                'fechacompletado' => '2026-03-02 13:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 47,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Curso MOOC – Inteligencia Artificial Aplicada a la Salud',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_epg/mooc_ia_salud.jpg',
                'fechacreacion' => '2026-05-14 09:00:00',
                'fechainicio' => '2026-05-14 11:00:00',
                'fechafin' => '2026-05-18 18:00:00',
                'fechacompletado' => '2026-05-18 15:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 48,
                'idadmin' => 1,
                'idempleado' => 13,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Conferencia Virtual – "El Sistema Administrativo de Planeamiento Estratégico en el Perú"',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_epg/conferencia_planeamiento_estrategico.jpg',
                'fechacreacion' => '2026-03-14 11:00:00',
                'fechainicio' => '2026-03-15 09:00:00',
                'fechafin' => '2026-03-18 18:00:00',
                'fechacompletado' => '2026-03-18 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // SERVICIO PSICOPEDAGÓGICO
            [
                'idrequerimiento' => 49,
                'idadmin' => 1,
                'idempleado' => 7,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Taller de Salud Mental "Regulación Emocional y Prevención de Conductas Autodestructivas"',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_psico/taller_salud_mental_regulacion.jpg',
                'fechacreacion' => '2026-04-28 09:00:00',
                'fechainicio' => '2026-04-28 11:00:00',
                'fechafin' => '2026-05-02 18:00:00',
                'fechacompletado' => '2026-05-02 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 50,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => '1ª Conferencia Psicopedagógica "GPS Emocional" – Campus Ica (Presencial)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_psico/conferencia_gps_emocional.jpg',
                'fechacreacion' => '2026-04-28 10:00:00',
                'fechainicio' => '2026-04-28 14:00:00',
                'fechafin' => '2026-05-02 18:00:00',
                'fechacompletado' => '2026-05-02 15:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 51,
                'idadmin' => 1,
                'idempleado' => 6,
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Infografía Actividades Servicio Psicopedagógico 2026-I',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Se reordenaron las actividades por fecha y se añadió link al aula virtual.',
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_psico/infografia_actividades_psico.jpg',
                'fechacreacion' => '2026-04-28 11:00:00',
                'fechainicio' => '2026-04-29 09:00:00',
                'fechafin' => '2026-05-03 18:00:00',
                'fechacompletado' => '2026-05-03 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 52,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Taller "Match Vocacional: Conecta con la Carrera que Sí es para Ti" – Campus Ica',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/drive/folders/uai_psico/taller_match_vocacional.jpg',
                'fechacreacion' => '2026-05-28 09:00:00',
                'fechainicio' => '2026-05-28 11:00:00',
                'fechafin' => '2026-06-01 18:00:00',
                'fechacompletado' => '2026-06-01 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
        ];

        $this->db->table('atencion')->insertBatch($data);
    }
}