<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AtencionSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('TRUNCATE TABLE atencion RESTART IDENTITY CASCADE');

        $data = [
            // Requerimiento 1: Campaña Verano - Más antiguo (Estado: finalizado)
            [

                'idrequerimiento' => 1,
                'idadmin' => 1,
                'idempleado' => 6, // Nicol - completado y entregado al cliente
                'idservicio' => 3,
                'idarea_agencia' => 3, // Creación de Contenido
                'servicio_personalizado' => 'Campaña Intriga Verano',
                'titulo' => 'Lanzamiento Colección 2026',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/campaña_verano_final.zip',
                'fechacreacion' => '2026-03-01 09:00:00',
                'fechainicio' => '2026-03-02 09:00:00',
                'fechafin' => '2026-03-08 17:00:00', // Terminó y envió a revisión
                'fechacompletado' => '2026-03-09 11:30:00', // Cliente aprobó y se completó
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // Requerimiento 2: Video Reel Bienvenida - Intermedio (Estado: en_revision)
            [
                'idrequerimiento' => 2,
                'idadmin' => 1,
                'idempleado' => 7, // Sonia - terminó y envió a revisión
                'idservicio' => 2,
                'idarea_agencia' => 2, // Edición y Video
                'servicio_personalizado' => null,
                'titulo' => 'Video Reel Bienvenida',
                'prioridad' => 'Alta',
                'estado' => 'en_revision',
                'num_modificaciones' => 1,
                'observacion_revision' => 'Cliente solicita cambiar música de fondo',
                'url_entrega' => 'https://drive.google.com/entrega/reel_bienvenida_v1.mp4',
                'fechacreacion' => '2026-03-15 11:00:00',
                'fechainicio' => '2026-03-16 10:00:00',
                'fechafin' => '2026-03-20 16:30:00', // Terminó y envió a revisión
                'fechacompletado' => null,
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // Requerimiento 3: Logo Aniversario UAI - Más nuevo (Estado: en_proceso)
            [
                'idrequerimiento' => 3,
                'idadmin' => 1,
                'idempleado' => 10, // Fabrizio - trabajando actualmente
                'idservicio' => 1,
                'idarea_agencia' => 1, // Diseño Gráfico
                'servicio_personalizado' => null,
                'titulo' => 'Logo Aniversario UAI',
                'prioridad' => 'Media',
                'estado' => 'en_proceso',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => null,
                'fechacreacion' => '2026-03-21 09:00:00',
                'fechainicio' => '2026-03-22 14:00:00',
                'fechafin' => null, // Aún no termina
                'fechacompletado' => null,
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // Requerimiento 4: Infografía Académica - Usuario 14 (Estado: pendiente_sin_asignar)
            [
                'idrequerimiento' => 4,
                'idadmin' => 1,
                'idempleado' => null, // Aún no asignado
                'idservicio' => 1,
                'idarea_agencia' => 1, // Diseño Gráfico
                'servicio_personalizado' => null,
                'titulo' => 'Infografía Académica',
                'prioridad' => 'Media',
                'estado' => 'pendiente_sin_asignar',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => null,
                'fechacreacion' => '2026-03-25 10:00:00',
                'fechainicio' => null,
                'fechafin' => null,
                'fechacompletado' => null,
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            //REQUERIMIENTOS DE PRUEBA

            // ============ LUNES 5 DE MAYO ============
            // Atención 1 - Banner Web
            [
                'idrequerimiento' => 5,
                'idadmin' => 1,
                'idempleado' => 6,    // Nicol - Creación de Contenido
                'idservicio' => 3,
                'idarea_agencia' => 3,
                'servicio_personalizado' => 'Campaña Intriga Verano',
                'titulo' => 'Lanzamiento Colección 2026',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/campaña_verano.zip',
                'fechacreacion' => '2026-03-01 09:00:00',
                'fechainicio' => '2026-03-02 09:00:00',
                'fechafin' => '2026-03-08 17:00:00',
                'fechacompletado' => '2026-03-09 11:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],


            // --- LUNES 4 MAYO: 1 tarea finalizada ---
            [
                'idrequerimiento' => 6,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Lunes (1)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/banner_lun_1.png',
                'fechacreacion' => '2026-05-04 08:00:00',
                'fechainicio' => '2026-05-04 08:30:00',
                'fechafin' => '2026-05-04 15:00:00',
                'fechacompletado' => '2026-05-04 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // --- MARTES 5 MAYO: 3 tareas finalizadas ---
            [
                'idrequerimiento' => 7,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Web Promoción Mayo (1)',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/banner_mar_1.png',
                'fechacreacion' => '2026-05-05 07:00:00',
                'fechainicio' => '2026-05-05 08:00:00',
                'fechafin' => '2026-05-05 12:00:00',
                'fechacompletado' => '2026-05-05 13:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 8,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Evento Martes (2)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/flyer_mar_2.png',
                'fechacreacion' => '2026-05-05 08:00:00',
                'fechainicio' => '2026-05-05 09:00:00',
                'fechafin' => '2026-05-05 14:00:00',
                'fechacompletado' => '2026-05-05 15:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 9,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Rediseño Logo Martes (3)',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/logo_mar_3.zip',
                'fechacreacion' => '2026-05-05 09:00:00',
                'fechainicio' => '2026-05-05 10:00:00',
                'fechafin' => '2026-05-05 17:00:00',
                'fechacompletado' => '2026-05-05 18:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // --- MIÉRCOLES 6 MAYO: 2 tareas finalizadas ---
            [
                'idrequerimiento' => 10,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Iconos RRSS Miércoles (1)',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/iconos_mie_1.zip',
                'fechacreacion' => '2026-05-06 08:00:00',
                'fechainicio' => '2026-05-06 09:00:00',
                'fechafin' => '2026-05-06 13:00:00',
                'fechacompletado' => '2026-05-06 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 11,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Post Campaña Miércoles (2)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/post_mie_2.jpg',
                'fechacreacion' => '2026-05-06 10:00:00',
                'fechainicio' => '2026-05-06 11:00:00',
                'fechafin' => '2026-05-06 17:00:00',
                'fechacompletado' => '2026-05-06 18:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // --- JUEVES 7 MAYO: 4 tareas finalizadas ---
            [
                'idrequerimiento' => 12,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Digital Jueves (1)',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/banner_jue_1.png',
                'fechacreacion' => '2026-05-07 07:00:00',
                'fechainicio' => '2026-05-07 07:30:00',
                'fechafin' => '2026-05-07 11:00:00',
                'fechacompletado' => '2026-05-07 12:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 13,
                'idadmin' => 1,
                'idempleado' => 11,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Descuento Jueves (2)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/flyer_jue_2.png',
                'fechacreacion' => '2026-05-07 08:00:00',
                'fechainicio' => '2026-05-07 09:00:00',
                'fechafin' => '2026-05-07 13:00:00',
                'fechacompletado' => '2026-05-07 14:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 14,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Logo Empresa Jueves (3)',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/logo_jue_3.ai',
                'fechacreacion' => '2026-05-07 09:00:00',
                'fechainicio' => '2026-05-07 10:00:00',
                'fechafin' => '2026-05-07 15:00:00',
                'fechacompletado' => '2026-05-07 16:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 15,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Infografía Proceso Jueves (4)',
                'prioridad' => 'Baja',
                'estado' => 'finalizado',
                'num_modificaciones' => 2,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/info_jue_4.png',
                'fechacreacion' => '2026-05-07 11:00:00',
                'fechainicio' => '2026-05-07 12:00:00',
                'fechafin' => '2026-05-07 18:00:00',
                'fechacompletado' => '2026-05-07 19:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],

            // --- VIERNES 8 MAYO: 2 tareas finalizadas ---
            [
                'idrequerimiento' => 16,
                'idadmin' => 1,
                'idempleado' => 10,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Infografía Estadísticas Viernes (1)',
                'prioridad' => 'Media',
                'estado' => 'finalizado',
                'num_modificaciones' => 1,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/info_vie_1.png',
                'fechacreacion' => '2026-05-08 08:00:00',
                'fechainicio' => '2026-05-08 09:00:00',
                'fechafin' => '2026-05-08 14:00:00',
                'fechacompletado' => '2026-05-08 15:30:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            [
                'idrequerimiento' => 17,
                'idadmin' => 1,
                'idempleado' => 12,
                'idservicio' => 1,
                'idarea_agencia' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Semestral Viernes (2)',
                'prioridad' => 'Alta',
                'estado' => 'finalizado',
                'num_modificaciones' => 0,
                'observacion_revision' => null,
                'url_entrega' => 'https://drive.google.com/banner_vie_2.png',
                'fechacreacion' => '2026-05-08 10:00:00',
                'fechainicio' => '2026-05-08 11:00:00',
                'fechafin' => '2026-05-08 17:00:00',
                'fechacompletado' => '2026-05-08 18:00:00',
                'cancelacionmotivo' => null,
                'fechacancelacion' => null,
            ],
            // --- ATENCIONES DE PRUEBA SLA (TODOS EN COLUMNA 1: NUEVAS SOLICITUDES) ---
            [
                'idrequerimiento'        => 5,
                'idadmin'                => 1,
                'idempleado'             => null,
                'idservicio'             => 1,
                'idarea_agencia'         => 1,
                'servicio_personalizado' => null,
                'titulo'                 => 'TEST: PEDIDO ATRASADO',
                'prioridad'              => 'Alta',
                'estado'                 => 'pendiente_sin_asignar',
                'num_modificaciones'     => 0,
                'observacion_revision'   => null,
                'url_entrega'            => null,
                'fechacreacion'          => '2026-05-01 10:00:00',
                'fechainicio'            => null,
                'fechafin'               => null,
                'fechacompletado'        => null,
                'cancelacionmotivo'      => null,
                'fechacancelacion'       => null,
            ],
            [
                'idrequerimiento'        => 6,
                'idadmin'                => 1,
                'idempleado'             => null,
                'idservicio'             => 1,
                'idarea_agencia'         => 1,
                'servicio_personalizado' => null,
                'titulo'                 => 'TEST: VENCE HOY',
                'prioridad'              => 'Media',
                'estado'                 => 'pendiente_sin_asignar',
                'num_modificaciones'     => 0,
                'observacion_revision'   => null,
                'url_entrega'            => null,
                'fechacreacion'          => '2026-05-11 08:00:00',
                'fechainicio'            => null,
                'fechafin'               => null,
                'fechacompletado'        => null,
                'cancelacionmotivo'      => null,
                'fechacancelacion'       => null,
            ],
            [
                'idrequerimiento'        => 7,
                'idadmin'                => 1,
                'idempleado'             => null,
                'idservicio'             => 1,
                'idarea_agencia'         => 1,
                'servicio_personalizado' => null,
                'titulo'                 => 'TEST: VENCE MAÑANA',
                'prioridad'              => 'Media',
                'estado'                 => 'pendiente_sin_asignar',
                'num_modificaciones'     => 0,
                'observacion_revision'   => null,
                'url_entrega'            => null,
                'fechacreacion'          => '2026-05-11 08:00:00',
                'fechainicio'            => null,
                'fechafin'               => null,
                'fechacompletado'        => null,
                'cancelacionmotivo'      => null,
                'fechacancelacion'       => null,
            ],
            [
                'idrequerimiento'        => 8,
                'idadmin'                => 1,
                'idempleado'             => null,
                'idservicio'             => 1,
                'idarea_agencia'         => 1,
                'servicio_personalizado' => null,
                'titulo'                 => 'TEST: EN TIEMPO',
                'prioridad'              => 'Baja',
                'estado'                 => 'pendiente_sin_asignar',
                'num_modificaciones'     => 0,
                'observacion_revision'   => null,
                'url_entrega'            => null,
                'fechacreacion'          => '2026-05-11 08:00:00',
                'fechainicio'            => null,
                'fechafin'               => null,
                'fechacompletado'        => null,
                'cancelacionmotivo'      => null,
                'fechacancelacion'       => null,
            ],
        ];

        $this->db->table('atencion')->insertBatch($data);
    }
}