<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RequerimientoSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('TRUNCATE TABLE requerimiento RESTART IDENTITY CASCADE');

        $data = [

            /* UAI */

            /* ADMINISTRACIÓN FINANCIERA Y TALENTO HUMANO - CRISTINA VIVIANA CASTILLO SANCHEZ */
            [
                'idusuarioempresa' => 14,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Piezas Días Festivos Febrero 2026 – Talento Humano',
                'objetivo_comunicacion' => 'Difundir saludos por: Día del Abogado (3/2), Día contra el Cáncer (4/2), San Valentín (14/2) y Día contra Hostigamiento Sexual (27/2 - video corto).',
                'descripcion' => 'Creación de arte. Logo Gestión del Talento. Canal: redes sociales. Dirigido a todos los colaboradores.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Redes sociales"]',
                'publico_objetivo' => 'Colaboradores UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-01-26 10:00:00',
                'fecharequerida' => '2026-01-29 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 14,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Formulario Identificación Miembros de Mesa – Colaboradores',
                'objetivo_comunicacion' => 'Identificar qué colaboradores han sido designados como miembros de mesa en las elecciones.',
                'descripcion' => 'Creación de arte. Historia de WhatsApp. Texto: "Si eres miembro de mesa, completa el siguiente formulario".',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Historia de Whatsapp"]',
                'publico_objetivo' => 'Todos los colaboradores UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-01-27 09:00:00',
                'fecharequerida' => '2026-01-29 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 14,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Invitación After Office – Día del Trabajador 29/04',
                'objetivo_comunicacion' => 'Invitar a las mamás colaboradoras UAI a la cena por el Día de la Madre el 08/05 en Restaurante El Olivar.',
                'descripcion' => 'Creación de arte. Hora: 7:00 p.m. Canal: redes sociales. Formato emailing.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Redes sociales"]',
                'publico_objetivo' => 'Mamás colaboradoras UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-27 10:00:00',
                'fecharequerida' => '2026-04-29 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 14,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Capacitación Virtual "Procedimientos Administrativos en Atención al Público"',
                'objetivo_comunicacion' => 'Convocar a colaboradores a capacitación virtual el jueves 12 a las 10:00 a.m.',
                'descripcion' => 'Creación de arte. Historia de WhatsApp para difusión interna. Logo Talento Humano UAI.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Historia de Whatsapp"]',
                'publico_objetivo' => 'Colaboradores UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-02-09 09:00:00',
                'fecharequerida' => '2026-02-10 18:00:00',
                'prioridad' => 'Media',
            ],

            /* AREA COMERCIAL - ALLISSON ZAMORA LUYO */
            [
                'idusuarioempresa' => 15,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Convenio Institucional – Policía Nacional del Perú',
                'objetivo_comunicacion' => 'Comunicar beneficio de 30% de descuento en posgrado para personal PNP mediante el convenio vigente.',
                'descripcion' => 'Creación de arte. Base en modelo referencial Ejército. Incluir programas de posgrado y datos de contacto 922833361.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Página web","Correo"]',
                'publico_objetivo' => 'Personal de la Policía Nacional del Perú',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-03-10 09:00:00',
                'fecharequerida' => '2026-03-12 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Plantilla Charla Virtual Posgrado – Editable Canva',
                'objetivo_comunicacion' => 'Contar con plantilla Canva estandarizada para charlas informativas de posgrado actualizables.',
                'descripcion' => 'Incluir campos editables: título, fecha, hora, imagen referencial, modalidad distancia, dirigido a, número 922833361. Mantener línea gráfica posgrado.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Profesionales y egresados interesados en posgrado',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["PNG"]',
                'fechacreacion' => '2026-02-18 10:00:00',
                'fecharequerida' => '2026-02-21 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Guía Rápida Pregrado A5 – Actualización Campus y Modalidades',
                'objetivo_comunicacion' => 'Actualizar guía rápida A5 con 5 campus (Chincha Alta, Chincha-Sunampe, Ica Centro, Ica Sur, Huaura) y añadir modalidades Híbrido y A Distancia.',
                'descripcion' => 'Adaptación de arte previo. Eliminar sección de talleres y reorganizar espacios. Para impresión.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Impresión física"]',
                'publico_objetivo' => 'Postulantes e interesados en pregrado UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-18 09:00:00',
                'fecharequerida' => '2026-05-20 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Convenio Corporativo Colegio de Obstetras de Huánuco',
                'objetivo_comunicacion' => 'Presentar beneficio corporativo 2026-I a obstetras de Huánuco: descuento en primer ciclo con mínimo 10 inscritos.',
                'descripcion' => 'Creación de arte. Incluir maestrías, SEP, doctorados. Licenciados SUNEDU. Número de contacto: 922833361.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Obstetras miembros del Colegio de Obstetras de Huánuco',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-02-18 11:00:00',
                'fecharequerida' => '2026-02-21 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Examen de Admisión Pregrado 27 de junio',
                'objetivo_comunicacion' => 'Promover la inscripción al examen de admisión del 27 de junio para difusión por asesores vía WhatsApp.',
                'descripcion' => 'Creación de arte. Fecha 27/06 como mensaje principal. Diseño de alto impacto para WhatsApp.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Historia de Whatsapp"]',
                'publico_objetivo' => 'Prospectos, egresados de secundaria, interesados en pregrado',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-06-07 09:00:00',
                'fecharequerida' => '2026-06-09 18:00:00',
                'prioridad' => 'Alta',
            ],

            /* BIENESTAR UNIVERSITARIO -  JESSICA KHRISTEL FERNANDINI VALENZUELA */
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Postulación Beneficios Económicos 2026-1',
                'objetivo_comunicacion' => 'Atraer a estudiantes a postular al proceso de Beneficios Económicos 2026-1.',
                'descripcion' => 'Adaptación de arte previo (2025). Difundir por correo, redes sociales y Aula Virtual. Incluir fechas: modalidades de apoyo 05/01 al 10/01, recategorización 11/01 y 12/01.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Emailing","Aula Virtual"]',
                'publico_objetivo' => 'Estudiantes de pregrado UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-01-08 09:00:00',
                'fecharequerida' => '2026-01-10 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Comunicado Matrícula Regular Beneficios Económicos',
                'objetivo_comunicacion' => 'Informar que solo aplican a beneficios económicos los estudiantes con matrícula regular (no extemporánea).',
                'descripcion' => 'Creación de arte. Canal: correo y Aula Virtual. Público: comunidad universitaria. Texto oficial adjunto.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Emailing","Aula Virtual (Pop up)"]',
                'publico_objetivo' => 'Comunidad universitaria UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-01-28 10:00:00',
                'fecharequerida' => '2026-01-30 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Tutores Psicólogos Servicio Psicopedagógico',
                'objetivo_comunicacion' => 'Convocar psicólogos comprometidos con el bienestar estudiantil para el Servicio Psicopedagógico UAI.',
                'descripcion' => 'Creación de arte para difusión externa en redes sociales. Adjuntar enlace de formulario Google Forms.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Redes sociales"]',
                'publico_objetivo' => 'Comunidad en general - convocatoria externa',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-01-28 14:00:00',
                'fecharequerida' => '2026-01-31 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Deportistas Alta Competencia 2026-1',
                'objetivo_comunicacion' => 'Informar a jóvenes deportistas que la UAI abre convocatoria para ingresantes con talento en ajedrez, karate, atletismo y tenis de mesa.',
                'descripcion' => 'Adaptación de arte 2025. Difusión externa vía correo y Aula Virtual. Incluir disciplinas y beneficios institucionales.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Emailing","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Jóvenes postulantes con logros deportivos',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-01-28 09:30:00',
                'fecharequerida' => '2026-01-31 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Inicio Talleres Deportivos 2026-I – Sede Chincha',
                'objetivo_comunicacion' => 'Informar y motivar a estudiantes Sede Chincha a inscribirse en talleres deportivos: básquet, futsal, vóley, tenis de mesa, ajedrez, karate.',
                'descripcion' => 'Adaptación de arte 2025. Incluir fecha inicio 13 de abril, Local 2 Sede Chincha, logos UAI/Bienestar/Servicio Deportivo.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Emailing","Historia de Whatsapp","SIGU o Aula Virtual Estudiantes","Redes sociales"]',
                'publico_objetivo' => 'Estudiantes de pregrado – Sede Chincha',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-04-06 09:00:00',
                'fecharequerida' => '2026-04-09 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Comunicado Uso Correcto de Botiquines de Seguridad',
                'objetivo_comunicacion' => 'Informar a toda la comunidad sobre el uso indebido de botiquines detectado el 08/05 y reforzar normas de uso.',
                'descripcion' => 'Creación de arte urgente. Canal: correo y Aula Virtual. Adjuntar comunicado oficial DBURS. Tono institucional formal.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Emailing","Aula Virtual (Pop up)"]',
                'publico_objetivo' => 'Comunidad universitaria UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-08 11:00:00',
                'fecharequerida' => '2026-05-08 18:00:00',
                'prioridad' => 'Alta',
            ],

            /* COBRANZAS Y CAJA – MARYORITH CASTILLON DE LA CRUZ */
            [
                'idusuarioempresa' => 17,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Recordatorio 1ª Cuota Pregrado y Posgrado – Vence 13 de Abril',
                'objetivo_comunicacion' => 'Incentivar pago oportuno de la primera cuota antes del 13/04 en todas las sedes para evitar recargos moratorios.',
                'descripcion' => 'Adaptación de arte. 4 versiones por sede: Chincha/Ica/Sunampe (BBVA, BCP, Scotiabank, Caja Municipal Ica, Yape), Huaura (Scotiabank), Posgrado (BCP, Yape, Scotiabank).',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Estudiantes matriculados 2026-1 – tono amigable',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-01 09:00:00',
                'fecharequerida' => '2026-04-05 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 17,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Canales de Pago UAI 2026 – Volante A6 por Sede',
                'objetivo_comunicacion' => 'Difundir canales de pago de cuotas y matrícula para las distintas sedes (Chincha/Ica, Huaura, Posgrado).',
                'descripcion' => 'Adaptación de arte. Formato volante A6 (105x148mm) imprimible en hoja A4. 3 versiones por sede. Información de mora (S/. 0.12/día) y advertencia de correcta digitación.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Impresión física","Correo","Página web"]',
                'publico_objetivo' => 'Estudiantes UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-25 09:00:00',
                'fecharequerida' => '2026-05-28 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 17,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Físico Canales de Pago – Módulos de Atención',
                'objetivo_comunicacion' => 'Informar a visitantes y estudiantes en local los medios de pago disponibles (BCP, Yape, BBVA, Scotiabank, Caja Municipal Ica).',
                'descripcion' => 'Creación de arte. Formato Banner 2x1 y banner web portada. Correo información: cobranzas@autonomadeica.edu.pe.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Banner físico"]',
                'publico_objetivo' => 'Público en general que visita la UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-04-18 10:00:00',
                'fecharequerida' => '2026-04-22 18:00:00',
                'prioridad' => 'Baja',
            ],

            /* COORDINACIÓN ADMINISTRATIVA Y ACADÉMICA – FICA ISMAEL ALONSO JUNCO QUIJANDRIA */
            [
                'idusuarioempresa' => 18,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Concurso Público Selección Docente – FICA 2026-1',
                'objetivo_comunicacion' => 'Difundir proceso de concurso público de selección docente por contrato para las escuelas de la FICA.',
                'descripcion' => 'Creación de arte. Enlace referencia: https://autonomadeica.com/pregrado/convocatoria/2026-1/. Canal: correo. Público: profesionales con maestría o doctorado.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Profesionales con maestría o doctorado en áreas afines',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-02-09 09:00:00',
                'fecharequerida' => '2026-02-11 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 18,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Plantilla Guías de Laboratorio por Escuela Profesional – FICA',
                'objetivo_comunicacion' => 'Estandarizar formato Word editable para guías de laboratorio de las 8 escuelas de la FICA.',
                'descripcion' => 'Creación de arte. Un diseño por carrera (Administración, Finanzas, Contabilidad, Derecho, Ing. Civil, Sistemas, Industrial, Arquitectura). Entrega en formato Word.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Docentes"]',
                'publico_objetivo' => 'Docentes de las escuelas de la FICA',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-02-20 10:00:00',
                'fecharequerida' => '2026-02-24 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 18,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Comunicado Clases Virtuales Sábado 6 de Junio – Elecciones 2026',
                'objetivo_comunicacion' => 'Comunicar a docentes y estudiantes de la FICA que el sábado 6 de junio las clases serán en modalidad virtual por las Elecciones Generales 2026.',
                'descripcion' => 'Creación de arte. Canal: correo. Logo FICA y UAI.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Docentes y estudiantes de la FICA',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-06-01 09:00:00',
                'fecharequerida' => '2026-06-02 18:00:00',
                'prioridad' => 'Alta',
            ],

            /* ÁREA: DEFENSORÍA UNIVERSITARIA - FRANCHESCA YSABELA BARRAZA LY */
            [
                'idusuarioempresa' => 19,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Afiche Institucional Tolerancia Cero al Hostigamiento Sexual',
                'objetivo_comunicacion' => 'Sensibilizar y prevenir el hostigamiento sexual en la UAI. Difundir canales de denuncia: defensoria.universitaria@autonomadeica.edu.pe.',
                'descripcion' => 'Creación de arte para afiches físicos con protector acrílico. Pernos para fijación en cafetería, biblioteca, pasadizos, tópico y oficinas.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Letreros"]',
                'publico_objetivo' => 'Comunidad universitaria – tono institucional, claro y preventivo',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-01-27 10:00:00',
                'fecharequerida' => '2026-01-30 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 19,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer "¿Conoces tus Derechos Universitarios?" – Defensoría',
                'objetivo_comunicacion' => 'Informar y sensibilizar a la comunidad sobre el rol de la Defensoría Universitaria y los derechos que protege.',
                'descripcion' => 'Creación de arte. Incluir: orientación, atención de quejas, trato digno, acceso a información. Sedes: Chincha, Ica y Huaura.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes","SIGU o Aula Virtual Docentes"]',
                'publico_objetivo' => 'Estudiantes, docentes y personal administrativo',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-14 09:00:00',
                'fecharequerida' => '2026-04-17 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 19,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner "Tolerancia Cero" 2x1 – Defensoría (para afiche físico)',
                'objetivo_comunicacion' => 'Actualización del banner de hostigamiento sexual con iconos interactivos sobre canales y valores de la comunidad.',
                'descripcion' => 'Adaptación de arte previo. Banner 2x1. Incluir iconos: "Estamos para escucharte", "confidencialidad", "comunidad respetuosa", "hostigamiento es falta grave".',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Banner físico"]',
                'publico_objetivo' => 'Toda la comunidad universitaria – formal empático',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-06 11:00:00',
                'fecharequerida' => '2026-05-09 18:00:00',
                'prioridad' => 'Media',
            ],

            /* DIRECCIÓN DE CALIDAD – ELOISA CALLAO CUBILLAS */
            [
                'idusuarioempresa' => 20,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Encuesta de Satisfacción Matrícula 2026-I – Estudiantes',
                'objetivo_comunicacion' => 'Invitar a estudiantes matriculados 2026-I a participar en la encuesta de matrícula del 23/03 al 04/04.',
                'descripcion' => 'Adaptación de arte. Título: "Estamos escuchándote". Enlace: https://forms.office.com/r/1bNqGKcBvD. Logos institucionales.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["SIGU o Aula Virtual Estudiantes","Correo","Redes sociales"]',
                'publico_objetivo' => 'Estudiantes matriculados período 2026-I',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-03-14 09:00:00',
                'fecharequerida' => '2026-03-18 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 20,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Capacitación Acreditación SINEACE – Comités de Calidad 23 y 24 de Abril',
                'objetivo_comunicacion' => 'Convocar a miembros de comités de calidad a curso-taller de acreditación con Dra. Amparo Gutiérrez Rojas.',
                'descripcion' => 'Creación de arte. 3 talleres: 23/04 (09:00-13:00 y 15:00-19:00) y 24/04 (09:00-13:00). Aula 401-D. Certificación por asistencia 100%.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Docentes","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Comités de calidad de los programas de estudios UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-10 10:00:00',
                'fecharequerida' => '2026-04-14 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 20,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Capacitación ISO 21001 – Gestión de Riesgos con PUCP (1-2 junio)',
                'objetivo_comunicacion' => 'Informar al personal directivo y jefes sobre capacitación con el Instituto para la Calidad PUCP: 1 y 2 de junio, modalidad presencial.',
                'descripcion' => 'Creación de arte. Horario: 09:00-13:00 y 15:00-19:00. Difusión solo por correo.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Jefes y directores del personal administrativo UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-14 11:00:00',
                'fecharequerida' => '2026-05-18 18:00:00',
                'prioridad' => 'Media',
            ],

            /* MARKETING Y DISEÑO - LEANDRO JOSE MACHADO GARCIA */
            [
                'idusuarioempresa' => 21,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Creación Logo CreaLab',
                'objetivo_comunicacion' => 'Diseñar logo para la Unidad de Negocio "CreaLab" (cursos cortos para comunidad general). Debe generar inspiración y creatividad con sobriedad.',
                'descripcion' => 'Creación de arte. Sin materiales de referencia. Canales: correo, web y redes sociales.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","Página web","Redes sociales"]',
                'publico_objetivo' => 'Comunidad en general',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-01-22 10:00:00',
                'fecharequerida' => '2026-01-25 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 21,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Ciclo Cero "Contigo desde el Inicio" – Onboarding Cachimbos 2026-1',
                'objetivo_comunicacion' => 'Informar a estudiantes cachimbos sobre el programa de onboarding: actividades de psicopedagogía, competencias digitales, gestión universitaria y nivelación académica.',
                'descripcion' => 'Creación de arte. Formatos: afiche A4, brochure, JPG. Paleta azul noche y blanco. Tono amigable. Sin materiales.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Página web","Redes sociales","Impresión física"]',
                'publico_objetivo' => 'Estudiantes cachimbos – ingresantes 2026-1',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-01-22 11:00:00',
                'fecharequerida' => '2026-01-25 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 21,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Propuestas de Logo para Consultora Clienza',
                'objetivo_comunicacion' => 'Elaborar propuestas de logo para consultora "Clienza – Experiencia Comercial & Comunicación Comercial". Colores sobrios, tipografía formal y elegante.',
                'descripcion' => 'Creación de arte. Canales: web y redes sociales. Con referencias en imágenes adjuntas.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Página web","Redes sociales"]',
                'publico_objetivo' => 'Público en general',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG","PDF"]',
                'fechacreacion' => '2026-02-20 09:00:00',
                'fecharequerida' => '2026-02-23 18:00:00',
                'prioridad' => 'Media',
            ],

            /* RESPONSABILIDAD SOCIAL – DAYANA IVET ROJAS GOÑI*/
            [
                'idusuarioempresa' => 22,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Voluntariado Universitario 2026-1',
                'objetivo_comunicacion' => 'Informar e invitar a estudiantes de 5to ciclo en adelante de Chincha e Ica a inscribirse en el Voluntariado UAI 2026.',
                'descripcion' => 'Creación de arte. Inscripciones: 8 al 16 de abril. Bienvenida a voluntarios: 22 de abril. Habilidades blandas, liderazgo, compromiso social.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes","Redes sociales"]',
                'publico_objetivo' => 'Estudiantes 5to ciclo en adelante – Campus Chincha e Ica',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-01 09:00:00',
                'fecharequerida' => '2026-04-05 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 22,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Reciclatón UAI 2026 – Día Mundial del Reciclaje',
                'objetivo_comunicacion' => 'Invitar a la comunidad universitaria al Reciclatón UAI el 21 de mayo en patios de Chincha e Ica.',
                'descripcion' => 'Creación de arte. Residuos aceptados: latas, papel, cartón, plástico. Logos institucionales.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes","Redes sociales"]',
                'publico_objetivo' => 'Estudiantes, docentes y personal administrativo UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-11 09:00:00',
                'fecharequerida' => '2026-05-14 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 22,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Tótem Triangular – Inclusión, Diversidad e Identidad de Género',
                'objetivo_comunicacion' => 'Diseño de totem triangular (0.50 cm ancho x 2 m alto) sobre inclusión, diversidad e identidad de género para espacios comunes.',
                'descripcion' => 'Creación de arte. Formato Illustrator editable y PDF. Descripción detallada en documento Word adjunto.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Banner físico"]',
                'publico_objetivo' => 'Comunidad universitaria – tono amigable',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-04-10 10:00:00',
                'fecharequerida' => '2026-04-14 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 22,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Pieza Gráfica "¿Cómo es la Responsabilidad Social en la UAI?"',
                'objetivo_comunicacion' => 'Comunicar a la comunidad universitaria en qué consiste la RS en la UAI.',
                'descripcion' => 'Creación de arte. Contenido basado en documento Word adjunto. Difusión por correo, redes sociales y Aula Virtual.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","Redes sociales","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Comunidad universitaria en general',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-18 11:00:00',
                'fecharequerida' => '2026-04-22 18:00:00',
                'prioridad' => 'Baja',
            ],
            [
                'idusuarioempresa' => 22,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'ECOCANJE UAI – Filial Ica',
                'objetivo_comunicacion' => 'Invitar a la comunidad universitaria de Filial Ica al ECOCANJE: entrega de reciclables a cambio de incentivos.',
                'descripcion' => 'Creación de arte con línea gráfica ecológica. Incluir fecha, horario, lugar y logos institucionales.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes","SIGU o Aula Virtual Docentes"]',
                'publico_objetivo' => 'Estudiantes, docentes y personal Filial Ica',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-05-29 09:00:00',
                'fecharequerida' => '2026-06-02 18:00:00',
                'prioridad' => 'Media',
            ],

            /* TÓPICO  – MARIA DEL ROSARIO FLORES ANCHANTE*/
            [
                'idusuarioempresa' => 23,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Adaptación Flyer Afiliación SIS – Campus Ica',
                'objetivo_comunicacion' => 'Informar a estudiantes del Campus Ica sobre el proceso de afiliación al SIS.',
                'descripcion' => 'Adaptación de arte 2025. Cambiar teléfono a 994172120, correo a servicio.salud.ica@autonomadeica.edu.pe y añadir "dirigido a estudiantes Campus Ica".',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Estudiantes Campus Ica – tono formal',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-01-15 09:00:00',
                'fecharequerida' => '2026-01-17 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 23,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Campaña Día Mundial del Glaucoma – Colaboradores UAI',
                'objetivo_comunicacion' => 'Difundir campaña preventiva de Glaucoma el 12 de marzo a las 10:00 a.m. para colaboradores mayores de 40 años.',
                'descripcion' => 'Creación de arte. Canal: redes sociales. Formato para difusión por grupo de WhatsApp. Incluir logo UAI.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Redes sociales","WhatsApp"]',
                'publico_objetivo' => 'Colaboradores UAI mayores de 40 años',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-03-04 10:00:00',
                'fecharequerida' => '2026-03-08 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 23,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Horario de Atención Tópico Sede Chincha – Celtex',
                'objetivo_comunicacion' => 'Publicar cartel con horario de atención: Lun-Sáb 7:30 am a 11:30 pm / Dom 7:30 am a 9:00 pm.',
                'descripcion' => 'Creación de arte en modelo celtex para letrero físico.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Letreros"]',
                'publico_objetivo' => 'Comunidad universitaria UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-04-25 11:00:00',
                'fecharequerida' => '2026-04-28 18:00:00',
                'prioridad' => 'Baja',
            ],
            [
                'idusuarioempresa' => 23,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => '1ª Campaña de Salud "Evita el Daño: Dile No a la Automedicación" – Campus Ica',
                'objetivo_comunicacion' => 'Invitar a estudiantes del Campus Ica a la primera campaña de salud vía Zoom (23 mayo) y presencial (25 mayo).',
                'descripcion' => 'Creación de arte. Ponentes: Equipo médico del servicio de salud. Logos Bienestar Universitario y Servicio de Salud.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Estudiantes de todos los programas – Campus Ica',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-13 09:00:00',
                'fecharequerida' => '2026-05-17 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 23,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Cartel Técnicas de Lavado de Manos – Celtex',
                'objetivo_comunicacion' => 'Difundir el procedimiento correcto del lavado de manos en espacios de la UAI.',
                'descripcion' => 'Creación de arte en modelo celtex para señalización. Incluir logos Servicio de Salud y Bienestar Universitario.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Banner físico","Letreros"]',
                'publico_objetivo' => 'Toda la comunidad UAI',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-04-25 14:00:00',
                'fecharequerida' => '2026-04-28 18:00:00',
                'prioridad' => 'Baja',
            ],

            /*  REGISTROS ACADÉMICOS – LENNY MARITE NANO INUMA  */
            [
                'idusuarioempresa' => 24,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Carné Universitario 2026-1',
                'objetivo_comunicacion' => 'Informar sobre la apertura de convocatoria para obtención, duplicado o actualización del carné universitario del 22/04 al 06/05.',
                'descripcion' => 'Adaptación de arte. Requisitos: vaucher + foto digital. Trámite vía plataforma intranet opción "Trámite". Correo: carneuniversitario@autonomadeica.edu.pe.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Correo","Redes sociales","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Estudiantes matriculados período 2026-1',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-14 09:00:00',
                'fecharequerida' => '2026-04-17 18:00:00',
                'prioridad' => 'Media',
            ],

            /* VÍNCULO UNIVERSITARIO – EMPRESA Y BOLSA DE TRABAJO – EDUARDO FRANCISCO TASAYCO MUÑOZ */
            [
                'idusuarioempresa' => 25,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Fondo Zoom Institucional – Interior y Exterior',
                'objetivo_comunicacion' => 'Contar con fondo virtual Zoom para reuniones nacionales e internacionales de la Dirección de Vinculación.',
                'descripcion' => 'Creación de arte. Dos versiones: nacional (UAI) e internacional (UAI – Perú). Incluir logo de la Dirección.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","Página web"]',
                'publico_objetivo' => 'Uso institucional – reuniones Zoom',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["PNG","JPG"]',
                'fechacreacion' => '2026-01-27 09:00:00',
                'fecharequerida' => '2026-01-30 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 25,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Plantilla Modelo Oferta Laboral – Estudiantes y Egresados',
                'objetivo_comunicacion' => 'Crear plantilla editable de oferta laboral con campos: empresa, perfil, fecha, requisitos, contacto.',
                'descripcion' => 'Creación de arte. Canales: correo, web, redes sociales, LinkedIn, Instagram. Dirigido a estudiantes y egresados UAI.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","Página web","Redes sociales","LinkedIn"]',
                'publico_objetivo' => 'Estudiantes y egresados UAI',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-02-18 10:00:00',
                'fecharequerida' => '2026-02-22 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 25,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Convocatoria Movilidad Internacional Académica y Pasantías 2026',
                'objetivo_comunicacion' => 'Convocar a todos los estudiantes UAI a postular a movilidad internacional, pasantías y similares.',
                'descripcion' => 'Adaptación de arte 2025. Actualizar fechas. Canales: correo, web, redes sociales, LinkedIn.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Correo","Página web","Redes sociales","LinkedIn"]',
                'publico_objetivo' => 'Todos los estudiantes de la Universidad',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-02-20 09:00:00',
                'fecharequerida' => '2026-02-24 18:00:00',
                'prioridad' => 'Alta',
            ],

            /* ESCUELA DE POSGRADO – GYANNELLA HUAMAN MENDOZA */
            [
                'idusuarioempresa' => 26,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Proceso de Matrícula Posgrado 2026-1',
                'objetivo_comunicacion' => 'Informar a estudiantes de posgrado sobre el proceso de matrícula del 23 de marzo al 4 de abril e inicio de clases el 6 de abril.',
                'descripcion' => 'Adaptación de arte 2025. Canales: SIGU, redes sociales, correo.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["SIGU o Aula Virtual Estudiantes","Redes sociales","Correo"]',
                'publico_objetivo' => 'Estudiantes de posgrado',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-03-14 09:00:00',
                'fecharequerida' => '2026-03-18 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 26,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Conferencia Virtual Posgrado – Psicología del Amor y Relaciones de Pareja',
                'objetivo_comunicacion' => 'Difundir conferencia virtual de la Maestría en Psicología Clínica para estudiantes e interesados.',
                'descripcion' => 'Adaptación de arte. Incluir datos del ponente, fecha, hora (7:00 p.m.), plataforma Zoom.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Correo"]',
                'publico_objetivo' => 'Estudiantes Maestría Psicología Clínica y público en general',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-02-27 10:00:00',
                'fecharequerida' => '2026-03-02 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 26,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Curso MOOC – Inteligencia Artificial Aplicada a la Salud',
                'objetivo_comunicacion' => 'Informar sobre curso gratuito de IA en Salud (32h) dirigido a maestrías y doctorados del área de salud.',
                'descripcion' => 'Creación de arte. Ponente: Mg. Luis Salazar Alvarado. Inicio: 25 de mayo. Plataforma: Aula Virtual.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["SIGU o Aula Virtual Estudiantes","Correo"]',
                'publico_objetivo' => 'Estudiantes de maestrías y doctorados en Salud Pública, Enfermería, Obstetricia',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-14 09:00:00',
                'fecharequerida' => '2026-05-18 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 26,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Conferencia Virtual – "El Sistema Administrativo de Planeamiento Estratégico en el Perú"',
                'objetivo_comunicacion' => 'Difundir conferencia virtual para estudiantes de Maestría en Gestión Pública el 24 de marzo a las 7:00 p.m.',
                'descripcion' => 'Adaptación de arte. Ponente: Mg. David Ashcallay Samaniego. Canal: correo y redes sociales.',
                'tipo_requerimiento' => 'Adaptación de Arte',
                'canales_difusion' => '["Correo","Redes sociales"]',
                'publico_objetivo' => 'Estudiantes Maestría Gestión Pública y público en general',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-03-14 11:00:00',
                'fecharequerida' => '2026-03-18 18:00:00',
                'prioridad' => 'Media',
            ],

            /*  SERVICIO PSICOPEDAGÓGICO – JANET MELISSA FIGUEROA GONZALES*/
            [
                'idusuarioempresa' => 27,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Taller de Salud Mental "Regulación Emocional y Prevención de Conductas Autodestructivas"',
                'objetivo_comunicacion' => 'Invitar a estudiantes al primer taller de salud mental el 11 de mayo a las 10:30 a.m. en el Auditorio UAI.',
                'descripcion' => 'Creación de arte. Ponente: Lic. Janet Figueroa Gonzales. Logos UAI y Servicio Psicopedagógico.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","Página web","Redes sociales"]',
                'publico_objetivo' => 'Estudiantes de todas las carreras y ciclos',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-28 09:00:00',
                'fecharequerida' => '2026-05-02 18:00:00',
                'prioridad' => 'Alta',
            ],
            [
                'idusuarioempresa' => 27,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => '1ª Conferencia Psicopedagógica "GPS Emocional" – Campus Ica (Presencial)',
                'objetivo_comunicacion' => 'Comunicar la realización de la primera conferencia psicopedagógica el 08/05/2026 a las 4:00 PM en Aula 101G.',
                'descripcion' => 'Creación de arte tipo flyer. Ponente: Lic. Lizbeth Zamora Quispe. Canales: correo y Aula Virtual.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Estudiantes de todos los ciclos y programas – Campus Ica',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-04-28 10:00:00',
                'fecharequerida' => '2026-05-02 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 27,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Infografía Actividades Servicio Psicopedagógico 2026-I',
                'objetivo_comunicacion' => 'Informar a estudiantes todas las actividades del servicio: tutorías socioemocionales, conferencias, talleres, orientación vocacional y proyecto de vida.',
                'descripcion' => 'Creación de arte tipo infografía. Contenido detallado en documento Word adjunto. Canal: correo, web, redes sociales y Aula Virtual.',
                'tipo_requerimiento' => 'Creación de Contenido',
                'canales_difusion' => '["Correo","Página web","Redes sociales","Aula Virtual (Pop up)"]',
                'publico_objetivo' => 'Estudiantes de todas las escuelas',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG","PNG"]',
                'fechacreacion' => '2026-04-28 11:00:00',
                'fecharequerida' => '2026-05-03 18:00:00',
                'prioridad' => 'Media',
            ],
            [
                'idusuarioempresa' => 27,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Taller "Match Vocacional: Conecta con la Carrera que Sí es para Ti" – Campus Ica',
                'objetivo_comunicacion' => 'Comunicar el taller de Orientación Vocacional el 10/06/2026 a las 4:00 PM, presencial, Aula 101G.',
                'descripcion' => 'Creación de arte tipo flyer. Ponente: Lic. Lizbeth Zamora. Logos UAI y Servicio Psicopedagógico.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Correo","SIGU o Aula Virtual Estudiantes"]',
                'publico_objetivo' => 'Estudiantes de primer y segundo ciclo de todos los programas',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-28 09:00:00',
                'fecharequerida' => '2026-06-01 18:00:00',
                'prioridad' => 'Media',
            ],
        ];
        $this->db->table('requerimiento')->insertBatch($data);
    }
}