<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RequerimientoSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('TRUNCATE TABLE requerimiento RESTART IDENTITY CASCADE');

        $data = [

            // SEMANA 1
            [
                'idusuarioempresa' => 13,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Web Admisión Q2',
                'objetivo_comunicacion' => 'Atraer tráfico a la web.',
                'descripcion' => 'Diseño de banner animado.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'Postulantes',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PNG"]',
                'fechacreacion' => '2026-05-01 09:00:00',
                'fecharequerida' => '2026-05-04 18:00:00',
                'prioridad' => 'Alta'
            ],
            [

                'idusuarioempresa' => 14,

                'idservicio' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Sesión Retratos Docentes',
                'objetivo_comunicacion' => 'Actualizar staff web.',
                'descripcion' => 'Sesión de fotos en campus.',
                'tipo_requerimiento' => 'Fotografía',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'Comunidad',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-01 10:00:00',
                'fecharequerida' => '2026-05-04 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Plan Content Mayo',
                'objetivo_comunicacion' => 'Engagement mensual.',
                'descripcion' => 'Calendario de posts.',
                'tipo_requerimiento' => 'Creacion de Contenido',
                'canales_difusion' => '["RRSS"]',
                'publico_objetivo' => 'Estudiantes',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-01 11:00:00',
                'fecharequerida' => '2026-05-04 18:00:00',
                'prioridad' => 'Baja'
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Flyer Taller Padres',
                'objetivo_comunicacion' => 'Convocatoria taller.',
                'descripcion' => 'Diseño de flyer informativo.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["WhatsApp"]',
                'publico_objetivo' => 'Padres',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-02 09:00:00',
                'fecharequerida' => '2026-05-05 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 17,
                'idservicio' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Video Institucional Short',
                'objetivo_comunicacion' => 'Branding colegio.',
                'descripcion' => 'Edición de video 30s.',
                'tipo_requerimiento' => 'Audiovisual',
                'canales_difusion' => '["Instagram"]',
                'publico_objetivo' => 'Padres potenciales',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["MP4"]',
                'fechacreacion' => '2026-05-02 10:00:00',
                'fecharequerida' => '2026-05-05 18:00:00',
                'prioridad' => 'Alta'
            ],
            [
                'idusuarioempresa' => 18,
                'idservicio' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Evento Deportivo',
                'objetivo_comunicacion' => 'Cobertura deportiva.',
                'descripcion' => 'Fotos de la final de fútbol.',
                'tipo_requerimiento' => 'Fotografía',
                'canales_difusion' => '["Facebook"]',
                'publico_objetivo' => 'Alumnos',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-03 09:00:00',
                'fecharequerida' => '2026-05-06 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 19,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Catálogo Invierno',
                'objetivo_comunicacion' => 'Ventas temporada.',
                'descripcion' => 'Diseño de catálogo digital.',
                'tipo_requerimiento' => 'Diseño Editorial',
                'canales_difusion' => '["WhatsApp"]',
                'publico_objetivo' => 'Clientes',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-03 10:00:00',
                'fecharequerida' => '2026-05-06 18:00:00',
                'prioridad' => 'Alta'
            ],
            [
                'idusuarioempresa' => 20,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Copywriting Ads',
                'objetivo_comunicacion' => 'Conversión anuncios.',
                'descripcion' => 'Textos para Facebook Ads.',
                'tipo_requerimiento' => 'Creacion de Contenido',
                'canales_difusion' => '["Ads"]',
                'publico_objetivo' => 'Compradores',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["Texto"]',
                'fechacreacion' => '2026-05-03 11:00:00',
                'fecharequerida' => '2026-05-06 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 21,
                'idservicio' => null,
                'servicio_personalizado' => 'Consultoría Estratégica',
                'titulo' => 'Plan Fidelización',
                'objetivo_comunicacion' => 'Retención clientes.',
                'descripcion' => 'Estrategia de puntos.',
                'tipo_requerimiento' => 'Personalizado',
                'canales_difusion' => '["Interno"]',
                'publico_objetivo' => 'Gerencia',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-03 14:00:00',
                'fecharequerida' => '2026-05-06 18:00:00',
                'prioridad' => 'Baja'
            ],
            [
                'idusuarioempresa' => 13,
                'idservicio' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Motion Graphic Logo',
                'objetivo_comunicacion' => 'Animación intro.',
                'descripcion' => 'Logo animado 5s.',
                'tipo_requerimiento' => 'Audiovisual',
                'canales_difusion' => '["Video"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["MP4"]',
                'fechacreacion' => '2026-05-04 09:00:00',
                'fecharequerida' => '2026-05-07 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 14,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Diploma Honor',
                'objetivo_comunicacion' => 'Reconocimiento.',
                'descripcion' => 'Diseño de diploma.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Físico"]',
                'publico_objetivo' => 'Alumnos',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-04 10:00:00',
                'fecharequerida' => '2026-05-07 18:00:00',
                'prioridad' => 'Baja'
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Stock Local',
                'objetivo_comunicacion' => 'Contenido web.',
                'descripcion' => 'Fotos de instalaciones.',
                'tipo_requerimiento' => 'Fotografía',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-04 11:00:00',
                'fecharequerida' => '2026-05-07 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Post Día Madre',
                'objetivo_comunicacion' => 'Saludo festivo.',
                'descripcion' => 'Diseño y copy post.',
                'tipo_requerimiento' => 'Creacion de Contenido',
                'canales_difusion' => '["RRSS"]',
                'publico_objetivo' => 'Madres',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-05 09:00:00',
                'fecharequerida' => '2026-05-08 18:00:00',
                'prioridad' => 'Alta'
            ],
            [
                'idusuarioempresa' => 17,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Etiquetas Productos',
                'objetivo_comunicacion' => 'Branding packaging.',
                'descripcion' => 'Diseño de etiquetas.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Físico"]',
                'publico_objetivo' => 'Clientes',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-05 10:00:00',
                'fecharequerida' => '2026-05-08 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 18,
                'idservicio' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Intro YouTube',
                'objetivo_comunicacion' => 'Identidad canal.',
                'descripcion' => 'Video intro 10s.',
                'tipo_requerimiento' => 'Audiovisual',
                'canales_difusion' => '["YouTube"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["MP4"]',
                'fechacreacion' => '2026-05-05 11:00:00',
                'fecharequerida' => '2026-05-08 18:00:00',
                'prioridad' => 'Baja'
            ],
            [
                'idusuarioempresa' => 19,
                'idservicio' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Outdoor',
                'objetivo_comunicacion' => 'Campaña exterior.',
                'descripcion' => 'Sesión fotos campo.',
                'tipo_requerimiento' => 'Fotografía',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-08 09:00:00',
                'fecharequerida' => '2026-05-11 18:00:00',
                'prioridad' => 'Alta'
            ],
            [
                'idusuarioempresa' => 20,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Banner Sale',
                'objetivo_comunicacion' => 'Anuncio descuentos.',
                'descripcion' => 'Diseño banner rojo.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'Clientes',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PNG"]',
                'fechacreacion' => '2026-05-08 10:00:00',
                'fecharequerida' => '2026-05-11 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 21,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Artículos Blog',
                'objetivo_comunicacion' => 'SEO mensual.',
                'descripcion' => '2 artículos SEO.',
                'tipo_requerimiento' => 'Creacion de Contenido',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["Texto"]',
                'fechacreacion' => '2026-05-08 11:00:00',
                'fecharequerida' => '2026-05-11 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 13,
                'idservicio' => null,
                'servicio_personalizado' => 'Rebranding Logo',
                'titulo' => 'Propuesta Logo 2',
                'objetivo_comunicacion' => 'Modernización.',
                'descripcion' => 'Segunda propuesta logo.',
                'tipo_requerimiento' => 'Personalizado',
                'canales_difusion' => '["Interno"]',
                'publico_objetivo' => 'Directivos',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-08 14:00:00',
                'fecharequerida' => '2026-05-11 18:00:00',
                'prioridad' => 'Alta'
            ],
            [
                'idusuarioempresa' => 14,
                'idservicio' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Loop Vitrina',
                'objetivo_comunicacion' => 'Atención local.',
                'descripcion' => 'Animación loop 10s.',
                'tipo_requerimiento' => 'Audiovisual',
                'canales_difusion' => '["Local"]',
                'publico_objetivo' => 'Peatones',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["MP4"]',
                'fechacreacion' => '2026-05-09 09:00:00',
                'fecharequerida' => '2026-05-12 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Tarjeta Presentación',
                'objetivo_comunicacion' => 'Networking.',
                'descripcion' => 'Diseño de tarjeta.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Físico"]',
                'publico_objetivo' => 'Staff',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-09 10:00:00',
                'fecharequerida' => '2026-05-12 18:00:00',
                'prioridad' => 'Baja'
            ],
            [
                'idusuarioempresa' => 16,
                'idservicio' => 4,
                'servicio_personalizado' => null,
                'titulo' => 'Fotos Productos',
                'objetivo_comunicacion' => 'Ventas catálogo.',
                'descripcion' => 'Fotos fondo blanco.',
                'tipo_requerimiento' => 'Fotografía',
                'canales_difusion' => '["Web"]',
                'publico_objetivo' => 'Clientes',
                'tiene_materiales' => false,
                'url_subida' => null,
                'formatos_solicitados' => '["JPG"]',
                'fechacreacion' => '2026-05-10 09:00:00',
                'fecharequerida' => '2026-05-13 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 17,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'News Mensual',
                'objetivo_comunicacion' => 'Fidelización.',
                'descripcion' => 'Redacción boletín.',
                'tipo_requerimiento' => 'Creacion de Contenido',
                'canales_difusion' => '["Mail"]',
                'publico_objetivo' => 'Suscriptores',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["Texto"]',
                'fechacreacion' => '2026-05-10 10:00:00',
                'fecharequerida' => '2026-05-13 18:00:00',
                'prioridad' => 'Baja'
            ],
            [
                'idusuarioempresa' => 18,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Señalética Nueva',
                'objetivo_comunicacion' => 'Orden local.',
                'descripcion' => 'Diseño carteles.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Local"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-10 11:00:00',
                'fecharequerida' => '2026-05-13 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 19,
                'idservicio' => 2,
                'servicio_personalizado' => null,
                'titulo' => 'Reel Promo 14',
                'objetivo_comunicacion' => 'Promoción flash.',
                'descripcion' => 'Video reel 15s.',
                'tipo_requerimiento' => 'Audiovisual',
                'canales_difusion' => '["Reels"]',
                'publico_objetivo' => 'Jóvenes',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["MP4"]',
                'fechacreacion' => '2026-05-11 09:00:00',
                'fecharequerida' => '2026-05-14 18:00:00',
                'prioridad' => 'Alta'
            ],
            [
                'idusuarioempresa' => 14,
                'idservicio' => 1,
                'servicio_personalizado' => null,
                'titulo' => 'Manual Identidad Lite',
                'objetivo_comunicacion' => 'Uso correcto marca.',
                'descripcion' => 'Guía de 5 páginas.',
                'tipo_requerimiento' => 'Creación de Arte',
                'canales_difusion' => '["Interno"]',
                'publico_objetivo' => 'Staff',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-11 10:00:00',
                'fecharequerida' => '2026-05-14 18:00:00',
                'prioridad' => 'Media'
            ],
            [
                'idusuarioempresa' => 15,
                'idservicio' => 3,
                'servicio_personalizado' => null,
                'titulo' => 'Estrategia Reels Mayo',
                'objetivo_comunicacion' => 'Crecimiento orgánico.',
                'descripcion' => 'Plan de 4 reels.',
                'tipo_requerimiento' => 'Creacion de Contenido',
                'canales_difusion' => '["Instagram"]',
                'publico_objetivo' => 'General',
                'tiene_materiales' => true,
                'url_subida' => null,
                'formatos_solicitados' => '["PDF"]',
                'fechacreacion' => '2026-05-11 11:00:00',
                'fecharequerida' => '2026-05-14 18:00:00',
                'prioridad' => 'Baja'
            ],
        ];

        $this->db->table('requerimiento')->insertBatch($data);
    }
}