<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsuariosSeeder extends Seeder
{
    public function run()
    {
        $data = [

            // ID 1: ADMIN
            [
                'nombre' => 'NOEMI',
                'apellidos' => 'TORRES TINEDO',
                'correo' => '16noemitorres@gmail.com',
                'telefono' => '963604801',
                'tipodoc' => 'DNI',
                'numerodoc' => '76331600',
                'usuario' => '76331600',
                'clave' => password_hash('76331600', PASSWORD_DEFAULT),
                'rol' => 'administrador',
                'idarea_agencia' => null,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 2: ADMIN
            [
                'nombre' => 'ADMIN',
                'apellidos' => 'SUPER ADMIN',
                'correo' => 'rodrigofelix.fotografo@gmail.com',
                'telefono' => '931826325',
                'tipodoc' => 'DNI',
                'numerodoc' => '75843912',
                'usuario' => 'administrador',
                'clave' => password_hash('rf_admin', PASSWORD_DEFAULT),
                'rol' => 'administrador',
                'idarea_agencia' => null,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],

            // ID 3: RODRIGO (Fotografía, responsable)
            [
                'nombre' => 'RODRIGO ALEXANDER',
                'apellidos' => 'FELIX HUAMAN',
                'correo' => 'rodrigofelix.fotografo@gmail.com',
                'telefono' => '931826325',
                'tipodoc' => 'DNI',
                'numerodoc' => '75843912',
                'usuario' => 'rfelix_rf',
                'clave' => password_hash('rf_75843912', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 4,
                'idarea' => null,
                'esresponsable' => true,
                'estado' => true,
            ],
            // ID 4: NOEMI (Creación de Contenido)
            [
                'nombre' => 'NOEMI',
                'apellidos' => 'TORRES TINEDO',
                'correo' => '16noemitorres@gmail.com',
                'telefono' => '963604801',
                'tipodoc' => 'DNI',
                'numerodoc' => '76331600',
                'usuario' => 'ntorres_rf',
                'clave' => password_hash('rf_76331600', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 3,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 5: MARIA (Creación de Contenido)
            [
                'nombre' => 'MARIA',
                'apellidos' => 'PIA CASTILLA',
                'correo' => 'piacaslhi@gmail.com',
                'telefono' => '912902965',
                'tipodoc' => 'DNI',
                'numerodoc' => '73245532',
                'usuario' => 'mpia_rf',
                'clave' => password_hash('rf_73245532', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 3,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 6: JHENINFER (Creación de Contenido)
            [
                'nombre' => 'JHENINFER MIRELLI',
                'apellidos' => 'CCOICCA ALVAREZ',
                'correo' => 'mirelli@gmail.com',
                'telefono' => '958008832',
                'tipodoc' => 'DNI',
                'numerodoc' => '75491896',
                'usuario' => 'jalvarez_rf',
                'clave' => password_hash('rf_75491896', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 3,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 7: NICOL (Creación de Contenido, responsable)
            [
                'nombre' => 'NICOL MICHELLE',
                'apellidos' => 'GUERRERO TORREALBA',
                'correo' => 'michelle@gmail.com',
                'telefono' => '927704167',
                'tipodoc' => 'CE',
                'numerodoc' => '007524370',
                'usuario' => 'nguerrero_rf',
                'clave' => password_hash('rf_007524370', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 3,
                'idarea' => null,
                'esresponsable' => true,
                'estado' => true,
            ],
            // ID 8: SONIA (Edición y Postproducción)
            [
                'nombre' => 'SONIA ALEJANDRA',
                'apellidos' => 'TELLO ROJAS',
                'correo' => 'satrsonia@gmail.com',
                'telefono' => '959125670',
                'tipodoc' => 'DNI',
                'numerodoc' => '49049820',
                'usuario' => 'stello_rf',
                'clave' => password_hash('rf_49049820', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 2,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 9: JOSE (Edición y Postproducción)
            [
                'nombre' => 'JOSE',
                'apellidos' => 'GUERRA CHACÓN',
                'correo' => 'isaichachon695@gmail.com',
                'telefono' => '960733818',
                'tipodoc' => 'DNI',
                'numerodoc' => '75187044',
                'usuario' => 'jguerra_rf',
                'clave' => password_hash('rf_75187044', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 2,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 10: JONATHAN (Edición y Postproducción, responsable)
            [
                'nombre' => 'JONATHAN',
                'apellidos' => 'MEDINA CAMPOS',
                'correo' => 'paratodoslados.2025@gmail.com',
                'telefono' => '979127328',
                'tipodoc' => 'DNI',
                'numerodoc' => '72324643',
                'usuario' => 'jmedina_rf',
                'clave' => password_hash('rf_72324643', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 2,
                'idarea' => null,
                'esresponsable' => true,
                'estado' => true,
            ],
            // ID 11: FABRIZIO (Diseño Gráfico)
            [
                'nombre' => 'FABRIZIO',
                'apellidos' => 'RAMOS TIPISMANA',
                'correo' => 'fabrz1rt13@gmail.com',
                'telefono' => '979099569',
                'tipodoc' => 'DNI',
                'numerodoc' => '75832420',
                'usuario' => 'framos_rf',
                'clave' => password_hash('rf_75832420', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 1,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 12: NAYRU (Diseño Gráfico)
            [
                'nombre' => 'NAYRU',
                'apellidos' => 'GOMEZ MAGALLANES',
                'correo' => 'magallanesnayru@gmail.com',
                'telefono' => '902009682',
                'tipodoc' => 'DNI',
                'numerodoc' => '71992007',
                'usuario' => 'ngomez_rf',
                'clave' => password_hash('rf_71992007', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 1,
                'idarea' => null,
                'esresponsable' => true,
                'estado' => true,
            ],
            // ID 13: JESUS (Diseño Gráfico)
            [
                'nombre' => 'JESUS',
                'apellidos' => 'DE LA CRUZ GARCÍA',
                'correo' => 'gabrieljesusdelacruzgarcia@gmail.com',
                'telefono' => '937002191',
                'tipodoc' => 'DNI',
                'numerodoc' => '73009277',
                'usuario' => 'jdelacruz_rf',
                'clave' => password_hash('rf_73009277', PASSWORD_DEFAULT),
                'rol' => 'empleado',
                'idarea_agencia' => 1,
                'idarea' => null,
                'esresponsable' => false,
                'estado' => true,
            ],

            /* CLIENTES (representantes de empresa) */

            /* UAI */
            // ID 14 – ADMINISTRACIÓN FINANCIERA Y TALENTO HUMANO
            [
                'nombre' => 'CRISTINA VIVIANA',
                'apellidos' => 'CASTILLO SANCHEZ',
                'correo' => 'cristina.castillo@autonomadeica.edu.pe',
                'telefono' => '986474103',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100001',
                'usuario' => 'ccastillo_uai',
                'clave' => password_hash('uai_40100001', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 1,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 15 – ÁREA COMERCIAL
            [
                'nombre' => 'ALLISSON',
                'apellidos' => 'ZAMORA LUYO',
                'correo' => 'allisson.zamora@autonomadeica.edu.pe',
                'telefono' => '933967944',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100002',
                'usuario' => 'azamora_uai',
                'clave' => password_hash('uai_40100002', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 2,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 16 – BIENESTAR UNIVERSITARIO
            [
                'nombre' => 'JESSICA KHRISTEL',
                'apellidos' => 'FERNANDINI VALENZUELA',
                'correo' => 'jessica.fernandini@autonomadeica.edu.pe',
                'telefono' => '977309094',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100003',
                'usuario' => 'jfernandini_uai',
                'clave' => password_hash('uai_40100003', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 5,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 17 – COBRANZAS Y CAJA
            [
                'nombre' => 'MARYORITH',
                'apellidos' => 'CASTILLON DE LA CRUZ',
                'correo' => 'maryorith.castillon@autonomadeica.edu.pe',
                'telefono' => '949092015',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100004',
                'usuario' => 'mcastillon_uai',
                'clave' => password_hash('uai_40100004', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 6,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 18 – COORDINACIÓN ADMINISTRATIVA Y ACADÉMICA
            [
                'nombre' => 'ISMAEL ALONSO',
                'apellidos' => 'JUNCO QUIJANDRIA',
                'correo' => 'decanatura.fica@autonomadeica.edu.pe',
                'telefono' => '951376674',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100005',
                'usuario' => 'ijunco_uai',
                'clave' => password_hash('uai_40100005', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 11,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 19 – DEFENSORÍA UNIVERSITARIA
            [
                'nombre' => 'FRANCHESCA YSABELA',
                'apellidos' => 'BARRAZA LY',
                'correo' => 'franchesca.barraza@autonomadeica.edu.pe',
                'telefono' => '906097826',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100006',
                'usuario' => 'fbarraza_uai',
                'clave' => password_hash('uai_40100006', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 12,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 20 – DIRECCIÓN DE CALIDAD
            [
                'nombre' => 'ELOISA',
                'apellidos' => 'CALLAO CUBILLAS',
                'correo' => 'calidad@autonomadeica.edu.pe',
                'telefono' => '983490647',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100007',
                'usuario' => 'ecallao_uai',
                'clave' => password_hash('uai_40100007', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 15,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 21 – MARKETING Y DISEÑO
            [
                'nombre' => 'LEANDRO JOSE',
                'apellidos' => 'MACHADO GARCIA',
                'correo' => 'leandro.machado@autonomadeica.edu.pe',
                'telefono' => '994163219',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100010',
                'usuario' => 'lmachado_uai',
                'clave' => password_hash('uai_40100010', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 23,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 22 – RESPONSABILIDAD SOCIAL
            [
                'nombre' => 'DAYANA IVET',
                'apellidos' => 'ROJAS GOÑI',
                'correo' => 'responsabilidad.social@autonomadeica.edu.pe',
                'telefono' => '934568254',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100011',
                'usuario' => 'drojas_uai',
                'clave' => password_hash('uai_40100011', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 26,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 23 – TÓPICO 
            [
                'nombre' => 'MARIA DEL ROSARIO',
                'apellidos' => 'FLORES ANCHANTE',
                'correo' => 'servicio.salud.ica@autonomadeica.edu.pe',
                'telefono' => '987322831',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100012',
                'usuario' => 'mflores_uai',
                'clave' => password_hash('uai_40100012', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 30,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 24 – REGISTROS ACADÉMICOS
            [
                'nombre' => 'LENNY MARITE',
                'apellidos' => 'NANO INUMA',
                'correo' => 'registros.academicos@autonomadeica.edu.pe',
                'telefono' => '903229754',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100013',
                'usuario' => 'lnano_uai',
                'clave' => password_hash('uai_40100013', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 31,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 25 – VÍNCULO UNIVERSITARIO - EMPRESA Y BOLSA DE TRABAJO
            [
                'nombre' => 'EDUARDO FRANCISCO',
                'apellidos' => 'TASAYCO MUÑOZ',
                'correo' => 'dvue-bt@autonomadeica.edu.pe',
                'telefono' => '998879409',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100015',
                'usuario' => 'etasayco_uai',
                'clave' => password_hash('uai_40100015', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 33,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 26 – ESCUELA DE POSGRADO
            [
                'nombre' => 'GYANNELLA',
                'apellidos' => 'HUAMAN MENDOZA',
                'correo' => 'direccion.epg@autonomadeica.edu.pe',
                'telefono' => '932754204',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100019',
                'usuario' => 'ghuaman_uai',
                'clave' => password_hash('uai_40100019', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 49,
                'esresponsable' => true,
                'estado' => true,
            ],

            // ID 27 – SERVICIO PSICOPEDAGÓGICO
            [
                'nombre' => 'JANET MELISSA',
                'apellidos' => 'FIGUEROA GONZALES',
                'correo' => 'servicio.psicopedagogico@autonomadeica.edu.pe',
                'telefono' => '960988270',
                'tipodoc' => 'DNI',
                'numerodoc' => '40100020',
                'usuario' => 'jfigueroa_uai',
                'clave' => password_hash('uai_40100020', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 50,
                'esresponsable' => true,
                'estado' => true,
            ],


            /* ADA BYRON */
            // ID 28
            [
                'nombre' => 'LUIS',
                'apellidos' => 'MENDOZA RIVAS',
                'correo' => '62345678@byron.edu.pe',
                'telefono' => '999666333',
                'tipodoc' => 'DNI',
                'numerodoc' => '63456789',
                'usuario' => 'lmendoza_ab',
                'clave' => password_hash('ab_63456789', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 52,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 29
            [
                'nombre' => 'CARLOS',
                'apellidos' => 'PAREDES VELA',
                'correo' => '63456790@byron.edu.pe',
                'telefono' => '999555666',
                'tipodoc' => 'DNI',
                'numerodoc' => '63456790',
                'usuario' => 'cparedes_ab',
                'clave' => password_hash('ab_63456790', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 53,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 30
            [
                'nombre' => 'ELENA',
                'apellidos' => 'SOLIS BARRERA',
                'correo' => '63456791@byron.edu.pe',
                'telefono' => '999777888',
                'tipodoc' => 'DNI',
                'numerodoc' => '63456791',
                'usuario' => 'esolis_ab',
                'clave' => password_hash('ab_63456791', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 54,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 31
            [
                'nombre' => 'DIEGO',
                'apellidos' => 'TASAYCO HUACCAMAYTA',
                'correo' => '1552480@senati.pe',
                'telefono' => '999777888',
                'tipodoc' => 'DNI',
                'numerodoc' => '99999999',
                'usuario' => 'diego_ab',
                'clave' => password_hash('ab_99999999', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 51,
                'esresponsable' => false,
                'estado' => true,
            ],

            /* URBANO & MODERNO */
            // ID 32
            [
                'nombre' => 'CARLOS ALBERTO',
                'apellidos' => 'MENDOZA PALOMINO',
                'correo' => 'cmendoza@urbanoymoderno.com.pe',
                'telefono' => '955123456',
                'tipodoc' => 'DNI',
                'numerodoc' => '45678912',
                'usuario' => 'cmendoza_um',
                'clave' => password_hash('um_45678912', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 57,
                'esresponsable' => false,
                'estado' => true,
            ],

            // ID 33
            [
                'nombre' => 'MILAGROS ROCIO',
                'apellidos' => 'ANCHANTE GOMEZ',
                'correo' => 'manchante@urbanoymoderno.com.pe',
                'telefono' => '966789123',
                'tipodoc' => 'DNI',
                'numerodoc' => '71234567',
                'usuario' => 'manchante_um',
                'clave' => password_hash('um_71234567', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 58,
                'esresponsable' => false,
                'estado' => true,
            ],

            // ID 34
            [
                'nombre' => 'JORGE LUIS',
                'apellidos' => 'CARRANZA NAVARRO',
                'correo' => 'jcarranza@urbanoymoderno.com.pe',
                'telefono' => '977456789',
                'tipodoc' => 'DNI',
                'numerodoc' => '10234567',
                'usuario' => 'jcarranza_um',
                'clave' => password_hash('um_10234567', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 59,
                'esresponsable' => false,
                'estado' => true,
            ],
            // ID 35
            [
                'nombre' => 'SANDRO STEVEN',
                'apellidos' => 'RODRIGUEZ ANCHANTE',
                'correo' => 'rass060606@gmail.com',
                'telefono' => '953288331',
                'tipodoc' => 'DNI',
                'numerodoc' => '60745420',
                'usuario' => 'srodriguez_um',
                'clave' => password_hash('um_60745420', PASSWORD_DEFAULT),
                'rol' => 'cliente',
                'idarea_agencia' => null,
                'idarea' => 56,
                'esresponsable' => false,
                'estado' => true,
            ],
        ];

        $this->db->table('usuarios')->insertBatch($data);
    }
}