<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsuariosSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nombre'        => 'NOEMI',
                'apellidos'     => 'TORRES TINEDO',
                'correo'        => '16noemitorres@gmail.com',
                'telefono'      => '963604801',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '76331600',
                'usuario'       => 'ntorres_rf',
                'clave'         => password_hash('rf_76331600', PASSWORD_DEFAULT),
                'rol'           => 'administrador',
                'idarea'        => null,
                'esresponsable' => false,
                'estado'        => true,
            ],
            [
                'nombre'        => 'SONIA ALEJANDRA',
                'apellidos'     => 'TELLO ROJAS',
                'correo'        => 'satrsonia@gmail.com',
                'telefono'      => '959125670',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '49049820',
                'usuario'       => 'stello_rf',
                'clave'         => password_hash('rf_49049820', PASSWORD_DEFAULT),
                'rol'           => 'empleado',
                'idarea'        => 2,
                'esresponsable' => false,
                'estado'        => true,
            ],
            [
                'nombre'        => 'JOSE',
                'apellidos'     => 'GUERRA CHACÓN',
                'correo'        => 'isaichachon695@gmail.com',
                'telefono'      => '960733818',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '75187044',
                'usuario'       => 'jguerra_rf',
                'clave'         => password_hash('rf_75187044', PASSWORD_DEFAULT),
                'rol'           => 'empleado',
                'idarea'        => 2,
                'esresponsable' => false,
                'estado'        => true,
            ],
            [
                'nombre'        => 'JONATHAN',
                'apellidos'     => 'MEDINA CAMPOS',
                'correo'        => 'paratodoslados.2025@gmail.com',
                'telefono'      => '979127328',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '72324643',
                'usuario'       => 'jmedina_rf',
                'clave'         => password_hash('rf_72324643', PASSWORD_DEFAULT),
                'rol'           => 'empleado',
                'idarea'        => 2,
                'esresponsable' => true,
                'estado'        => true,
            ],
            [
                'nombre'        => 'FABRIZIO',
                'apellidos'     => 'RAMOS TIPISMANA',
                'correo'        => 'fabrz1rt13@gmail.com',
                'telefono'      => '979099569',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '75832420',
                'usuario'       => 'framos_rf',
                'clave'         => password_hash('rf_75832420', PASSWORD_DEFAULT),
                'rol'           => 'empleado',
                'idarea'        => 1,
                'esresponsable' => false,
                'estado'        => true,
            ],
            [
                'nombre'        => 'NAYRU',
                'apellidos'     => 'GOMEZ MAGALLANES',
                'correo'        => 'magallanesnayru@gmail.com',
                'telefono'      => '902009682',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '71992007',
                'usuario'       => 'ngomez_rf',
                'clave'         => password_hash('rf_71992007', PASSWORD_DEFAULT),
                'rol'           => 'empleado',
                'idarea'        => 1,
                'esresponsable' => false,
                'estado'        => true,
            ],
            [
                'nombre'        => 'JESUS',
                'apellidos'     => 'DE LA CRUZ GARCÍA',
                'correo'        => 'gabrieljesusdelacruzgarcia@gmail.com',
                'telefono'      => '937002191',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '73009277',
                'usuario'       => 'jdelacruz_rf',
                'clave'         => password_hash('rf_73009277', PASSWORD_DEFAULT),
                'rol'           => 'empleado',
                'idarea'        => 1,
                'esresponsable' => true,
                'estado'        => true,
            ],
            [
                'nombre'        => 'ANA',
                'apellidos'     => 'FLORES QUISPE',
                'correo'        => '62345678@uai.edu.pe',
                'telefono'      => '999888777',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '62345678',
                'usuario'       => 'aflores_rf',
                'clave'         => password_hash('rf_62345678', PASSWORD_DEFAULT),
                'rol'           => 'cliente',
                'idarea'        => null,
                'esresponsable' => false,
                'estado'        => true,
            ],
            [
                'nombre'        => 'LUIS',
                'apellidos'     => 'MENDOZA RIVAS',
                'correo'        => '62345678@byron.edu.pe',
                'telefono'      => '999666333',
                'tipodoc'       => 'DNI',
                'numerodoc'     => '63456789',
                'usuario'       => 'lmendoza_rf',
                'clave'         => password_hash('rf_63456789', PASSWORD_DEFAULT),
                'rol'           => 'cliente',
                'idarea'        => null,
                'esresponsable' => false,
                'estado'        => true,
            ],
        ];

        $this->db->table('usuarios')->insertBatch($data);
    }
}